; wEventFlags bit flags

	const_def
	
; The first eight flags are reset upon reloading the map
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_1
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_2
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_3
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_4
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_5
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_6
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_7
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_8
	
; Placeholders
	const EVENT_GOT_TM31_MUD_SLAP
	const EVENT_GOT_TM49_FURY_CUTTER
	const EVENT_GOT_TM01_DYNAMICPUNCH
	const EVENT_GOT_TM45_ATTRACT
	const EVENT_GOT_TM30_SHADOW_BALL
	const EVENT_GOT_TM23_IRON_TAIL
	const EVENT_GOT_TM51_CUT
	const EVENT_GOT_TM53_WHIRLPOOL
	const EVENT_GOT_TM54_WATERFALL	
	const EVENT_GOT_HM01_FLY
	const EVENT_GOT_HM02_SURF
	const EVENT_GOT_HM03_STRENGTH
	
; TMs
	const EVENT_DARK_CAVE_1F_TM08_ROCK_SMASH
	const EVENT_ROUTE_30_BERRY_HOUSE_TM05_ROAR
	const EVENT_LAKE_OF_RAGE_HIDDEN_POWER_HOUSE_TM10_HIDDEN_POWER
	const EVENT_ROUTE_45_TM12_SWEET_SCENT
	const EVENT_MAHOGANY_GYM_TM16_ICY_WIND
	const EVENT_ECRUTEAK_GYM_TM50_NIGHTMARE
	const EVENT_ELMS_LAB_TM51_CUT
	const EVENT_DARK_CAVE_1F_TM52_FLASH
	const EVENT_BURNED_TOWER_B1F_TM55_ANCIENTPOWER
	const EVENT_ROUTE_38_TM60_RAZOR_LEAF
	const EVENT_BLACKTHORN_GYM_1F_TM66_TWISTER
	const EVENT_LAKE_OF_RAGE_TM71_WHIRLWIND
	const EVENT_ECRUTEAK_POKECENTER_TM75_FALSE_SWIPE
	
; HMs

; Rods
	const EVENT_GOT_OLD_ROD
	const EVENT_GOT_GOOD_ROD
	const EVENT_GOT_SUPER_ROD
	
; Johto story events: Chapter 0
	const EVENT_INITIALIZED_EVENTS
	const EVENT_GOT_A_POKEMON_FROM_ELM
	const EVENT_GOT_VULPIX_FROM_ELM
	const EVENT_GOT_POLIWAG_FROM_ELM
	const EVENT_GOT_ODDISH_FROM_ELM
	const EVENT_ROUTE_30_BATTLE
	const EVENT_DARK_CAVE_1F_TATTERED_HAT
	const EVENT_GAVE_TATTERED_HAT_TO_ELM
	const EVENT_TALKED_TO_MOM_AFTER_TATTERED_HAT_QUEST
	const EVENT_DUDE_TALKED_TO_YOU
	const EVENT_LEARNED_TO_CATCH_POKEMON
	const EVENT_ELM_CALLED_ABOUT_STOLEN_POKEMON
	const EVENT_ROUTE_46_OPEN
	const EVENT_MET_TUSCANY_OF_TUESDAY
	const EVENT_GOT_PINK_BOW_FROM_TUSCANY
	
; Chapter 1
	const EVENT_MET_ROUTE_45_HEAL_HOUSE_GRANNY
	const EVENT_GOT_HONEY_DROP_FROM_GRANNY
	const EVENT_TALKED_TO_CLAIR_IN_DRAGON_SHRINE
	const EVENT_MET_SANTOS_OF_SATURDAY
	const EVENT_GOT_CLEANSE_TAG_FROM_SANTOS


; Chapter 2
	const EVENT_TALKED_TO_LORELEI
	const EVENT_ICE_PATH_MELTED_ICE
	const EVENT_ROUTE_43_GATE_GOT_QUICK_CLAW
	const EVENT_CLEARED_LAKE_OF_RAGE
	const EVENT_LAKE_OF_RAGE_GOT_PORYGON
	const EVENT_LAKE_OF_RAGE_GOT_UPGRADE
	const EVENT_MET_WESLEY_OF_WEDNESDAY
	const EVENT_GOT_BLACKBELT_FROM_WESLEY
	const EVENT_GOT_UP_GRADE
	const EVENT_ROUTE_42_ROCKETS_GONE

; Chapter 3
	const EVENT_BEAT_KIMONO_GIRLS
	const EVENT_DANCE_THEATRE_GOT_STONE
	const EVENT_ECRUTEAK_CITY_FISHER_EXP_CANDY_M
	const EVENT_SAVED_MOOMOO_FARM

; Chapter 4
	const EVENT_CLEARED_ROCKET_TOWER

; Chapter 5
	const EVENT_MORTY_IN_MT_MORTAR
	const EVENT_MORTY_IN_ECRUTEAK_GYM
	const EVENT_ECRUTEAK_CITY_SUDOWOODO1
	const EVENT_ECRUTEAK_CITY_SUDOWOODO2
	const EVENT_ECRUTEAK_CITY_CUT_TREES

; Chapter 6


; Chapter 7


; Chapter 8


	const EVENT_ETHAN_IN_MT_SILVER
	const EVENT_ETHAN_IN_NEW_BARK
	const EVENT_CLEARED_ROCKET_HIDEOUT ; placeholder
	const EVENT_JASMINE_RETURNED_TO_GYM ; DELETE
	const EVENT_CLEARED_RADIO_TOWER ; untouched
	const EVENT_GOT_SECRETPOTION_FROM_PHARMACY ; untouched
	const EVENT_GOT_SS_TICKET_FROM_ELM ; untouched
	const EVENT_USED_THE_CARD_KEY_IN_THE_RADIO_TOWER ; untouched
	const EVENT_MADE_WHITNEY_CRY ; untouched
	const EVENT_HERDED_FARFETCHD ; untouched
	const EVENT_FOUGHT_SUDOWOODO ; untouched
	const EVENT_CLEARED_SLOWPOKE_WELL ; untouched
	const EVENT_REFUSED_TO_TAKE_EGG_FROM_ELMS_AIDE ; untouched
	const EVENT_GOT_TOGEPI_EGG_FROM_ELMS_AIDE ; untouched
	const EVENT_MADE_UNOWN_APPEAR_IN_RUINS ; untouched
	const EVENT_FAST_SHIP_DESTINATION_OLIVINE ; untouched
	const EVENT_FAST_SHIP_FIRST_TIME ; DELETE
	const EVENT_FAST_SHIP_HAS_ARRIVED ; untouched
	const EVENT_FAST_SHIP_FOUND_GIRL ; untouched
	const EVENT_FAST_SHIP_LAZY_SAILOR ; untouched
	const EVENT_FAST_SHIP_INFORMED_ABOUT_LAZY_SAILOR ; untouched
	const EVENT_KURT_GAVE_YOU_LURE_BALL ; untouched
	const EVENT_JASMINE_EXPLAINED_AMPHYS_SICKNESS ; untouched
	const EVENT_BEAT_ELITE_FOUR ; untouched
	const EVENT_GOT_SHUCKIE ; untouched
	const EVENT_MANIA_TOOK_SHUCKIE_OR_LET_YOU_KEEP_HIM ; untouched
	const EVENT_GOT_SUNNY_DAY_FROM_RADIO_TOWER ; untouched
	const EVENT_GOT_PINK_BOW_FROM_MARY ; untouched
	const EVENT_USED_BASEMENT_KEY ; untouched
	const EVENT_RECEIVED_CARD_KEY ; untouched
	const EVENT_GOT_MYSTIC_WATER_IN_CHERRYGROVE ; untouched
	const EVENT_GOT_EEVEE ; untouched
	const EVENT_GOT_KENYA ; untouched
	const EVENT_GAVE_KENYA ; untouched
	const EVENT_GOT_HP_UP_FROM_RANDY ; untouched
	const EVENT_TOGEPI_HATCHED ; untouched
	const EVENT_SHOWED_TOGEPI_TO_ELM ; untouched
	const EVENT_GOT_EVERSTONE_FROM_ELM ; untouched
	const EVENT_GOT_TM36_SLUDGE_BOMB ; untouched
	const EVENT_GOT_ITEMFINDER ; untouched
	const EVENT_GOT_BICYCLE ; untouched
	const EVENT_GOT_SQUIRTBOTTLE ; untouched
	const EVENT_GOT_MIRACLE_SEED_IN_ROUTE_32 ; untouched
	const EVENT_GOT_CHARCOAL_IN_CHARCOAL_KILN ; untouched
	const EVENT_GOT_TM02_HEADBUTT ; untouched
	const EVENT_DECIDED_TO_HELP_LANCE ; untouched
	const EVENT_GOT_TYROGUE_FROM_KIYO ; untouched
	const EVENT_MET_FRIEDA_OF_FRIDAY ; untouched
	const EVENT_GOT_POISON_BARB_FROM_FRIEDA ; untouched
	const EVENT_MET_ARTHUR_OF_THURSDAY ; untouched
	const EVENT_GOT_HARD_STONE_FROM_ARTHUR ; untouched
	const EVENT_MET_SUNNY_OF_SUNDAY ; untouched
	const EVENT_GOT_MAGNET_FROM_SUNNY ; untouched
	const EVENT_MET_MONICA_OF_MONDAY ; untouched
	const EVENT_GOT_SHARP_BEAK_FROM_MONICA ; untouched
	const EVENT_GOT_SOFT_SAND_FROM_KATE ; untouched
	const EVENT_GOT_METAL_COAT_FROM_GRANDPA_ON_SS_AQUA ; untouched
	const EVENT_GOT_BLACKGLASSES_IN_DARK_CAVE ; untouched
	const EVENT_GOT_KINGS_ROCK_IN_SLOWPOKE_WELL ; untouched
	const EVENT_GOT_TM47_STEEL_WING ; untouched
	const EVENT_GOT_TM37_SANDSTORM ; untouched
	const EVENT_FIRST_TIME_BANKING_WITH_MOM ; untouched
	const EVENT_TOLD_ELM_ABOUT_TOGEPI_OVER_THE_PHONE ; untouched
	const EVENT_GOT_CLEAR_BELL ; untouched
	const EVENT_GOT_SILVER_WING ; untouched
	const EVENT_GOT_MASTER_BALL_FROM_ELM ; untouched
	const EVENT_MET_FLORIA ; untouched
	const EVENT_TALKED_TO_FLORIA_AT_FLOWER_SHOP ; untouched
	const EVENT_BUGGING_KURT_TOO_MUCH ; untouched
	const EVENT_TALKED_TO_RUINS_COWARD ; untouched
	const EVENT_CAN_GIVE_GS_BALL_TO_KURT ; untouched
	const EVENT_GAVE_GS_BALL_TO_KURT ; untouched
	const EVENT_FOREST_IS_RESTLESS ; untouched
	const EVENT_WARPED_FROM_ROUTE_35_NATIONAL_PARK_GATE ; untouched
	const EVENT_SWITCH_1 ; untouched
	const EVENT_SWITCH_2 ; untouched
	const EVENT_SWITCH_3 ; untouched
	const EVENT_EMERGENCY_SWITCH ; untouched
	const EVENT_SWITCH_4 ; untouched
	const EVENT_SWITCH_5 ; untouched
	const EVENT_SWITCH_6 ; untouched
	const EVENT_SWITCH_7 ; untouched
	const EVENT_SWITCH_8 ; untouched
	const EVENT_SWITCH_9 ; untouched
	const EVENT_SWITCH_10 ; untouched
	const EVENT_SWITCH_11 ; untouched
	const EVENT_SWITCH_12 ; untouched
	const EVENT_SWITCH_13 ; untouched
	const EVENT_SWITCH_14 ; untouched
	const EVENT_TURNED_OFF_SECURITY_CAMERAS ; untouched
	const EVENT_GOLDENROD_DEPT_STORE_B1F_LAYOUT_1 ; untouched
	const EVENT_GOLDENROD_DEPT_STORE_B1F_LAYOUT_2 ; untouched
	const EVENT_GOLDENROD_DEPT_STORE_B1F_LAYOUT_3 ; untouched
	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_BLOCKED_OFF ; untouched
	const EVENT_LEFT_MONS_WITH_CONTEST_OFFICER ; untouched
	const EVENT_WILLS_ROOM_ENTRANCE_CLOSED ; untouched
	const EVENT_WILLS_ROOM_EXIT_OPEN ; untouched
	const EVENT_KOGAS_ROOM_ENTRANCE_CLOSED ; untouched
	const EVENT_KOGAS_ROOM_EXIT_OPEN ; untouched
	const EVENT_BRUNOS_ROOM_ENTRANCE_CLOSED ; untouched
	const EVENT_BRUNOS_ROOM_EXIT_OPEN ; untouched
	const EVENT_KARENS_ROOM_ENTRANCE_CLOSED ; untouched
	const EVENT_KARENS_ROOM_EXIT_OPEN ; untouched
	const EVENT_LANCES_ROOM_ENTRANCE_CLOSED ; untouched
	const EVENT_LANCES_ROOM_EXIT_OPEN ; untouched
	const EVENT_CONTEST_OFFICER_HAS_SUN_STONE ; untouched
	const EVENT_CONTEST_OFFICER_HAS_EVERSTONE ; untouched
	const EVENT_CONTEST_OFFICER_HAS_GOLD_BERRY ; untouched
	const EVENT_CONTEST_OFFICER_HAS_BERRY ; untouched
	const EVENT_BEAT_RIVAL_IN_MT_MOON ; untouched
	const EVENT_MET_BILLS_GRANDPA ; untouched
	const EVENT_SHOWED_LICKITUNG_TO_BILLS_GRANDPA ; untouched
	const EVENT_SHOWED_ODDISH_TO_BILLS_GRANDPA ; untouched
	const EVENT_SHOWED_STARYU_TO_BILLS_GRANDPA ; untouched
	const EVENT_SHOWED_GROWLITHE_VULPIX_TO_BILLS_GRANDPA ; untouched
	const EVENT_SHOWED_PICHU_TO_BILLS_GRANDPA ; untouched
	const EVENT_GOT_EVERSTONE_FROM_BILLS_GRANDPA ; untouched
	const EVENT_GOT_LEAF_STONE_FROM_BILLS_GRANDPA ; untouched
	const EVENT_GOT_WATER_STONE_FROM_BILLS_GRANDPA ; untouched
	const EVENT_GOT_FIRE_STONE_FROM_BILLS_GRANDPA ; untouched
	const EVENT_GOT_THUNDERSTONE_FROM_BILLS_GRANDPA ; untouched
	const EVENT_LISTENED_TO_INITIAL_RADIO ; untouched
	const EVENT_WALL_OPENED_IN_HO_OH_CHAMBER ; untouched
	const EVENT_WALL_OPENED_IN_KABUTO_CHAMBER ; untouched
	const EVENT_WALL_OPENED_IN_OMANYTE_CHAMBER ; untouched
	const EVENT_WALL_OPENED_IN_AERODACTYL_CHAMBER ; untouched
	const EVENT_WELCOMED_TO_POKECOM_CENTER ; untouched
	const EVENT_WADE_HAS_BERRY ; untouched
	const EVENT_WADE_HAS_PSNCUREBERRY ; untouched
	const EVENT_WADE_HAS_PRZCUREBERRY ; untouched
	const EVENT_WADE_HAS_BITTER_BERRY ; untouched
	const EVENT_FOUGHT_EUSINE ; untouched
	const EVENT_KOJI_ALLOWS_YOU_PASSAGE_TO_TIN_TOWER ; untouched
	const EVENT_GOT_RAINBOW_WING ; untouched
	const EVENT_HUEY_PROTEIN ; untouched
	const EVENT_JOEY_HP_UP ; untouched
	const EVENT_PARRY_IRON ; untouched
	const EVENT_ERIN_CALCIUM ; untouched
	const EVENT_BUENA_OFFERED_HER_PHONE_NUMBER ; untouched
	const EVENT_MET_BUENA ; untouched
	const EVENT_GOT_ODD_EGG ; untouched
	const EVENT_GOT_GS_BALL_FROM_POKECOM_CENTER ; untouched
	const EVENT_KURTS_HOUSE_GRANDDAUGHTER_1 ; untouched
	const EVENT_KURTS_HOUSE_GRANDDAUGHTER_2 ; untouched
	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_FISHER ; untouched
	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_YOUNGSTERS ; untouched
	const EVENT_ROCKET_TOWER_BATTLE_ROOM_YOUNGSTER ; untouched
	const EVENT_PICKED_UP_GOLD_BERRY_FROM_HO_OH_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_MYSTERYBERRY_FROM_HO_OH_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_REVIVAL_HERB_FROM_HO_OH_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_CHARCOAL_FROM_HO_OH_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_BERRY_FROM_KABUTO_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_PSNCUREBERRY_FROM_KABUTO_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_HEAL_POWDER_FROM_KABUTO_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_ENERGYPOWDER_FROM_KABUTO_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_MYSTERYBERRY_FROM_OMANYTE_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_MYSTIC_WATER_FROM_OMANYTE_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_STARDUST_FROM_OMANYTE_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_STAR_PIECE_FROM_OMANYTE_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_GOLD_BERRY_FROM_AERODACTYL_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_MOON_STONE_FROM_AERODACTYL_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_HEAL_POWDER_FROM_AERODACTYL_ITEM_ROOM ; untouched
	const EVENT_PICKED_UP_ENERGY_ROOT_FROM_AERODACTYL_ITEM_ROOM ; untouched
	const EVENT_AZALEA_TOWN_KURT ; untouched
	const EVENT_ILEX_FOREST_KURT ; untouched
	const EVENT_MOUNT_MORTAR_B2F_MAX_POTION ; untouched
	const EVENT_MOUNT_MORTAR_B2F_NUGGET ; untouched
	const EVENT_ECRUTEAK_GYM_GRAMPS ; untouched
	const EVENT_ECRUTEAK_CITY_GRAMPS ; untouched
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_1 ; untouched
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_2 ; untouched
	const EVENT_CIANWOOD_CITY_EUSINE ; untouched
	const EVENT_SAW_SUICUNE_AT_CIANWOOD_CITY ; untouched
	const EVENT_SAW_SUICUNE_ON_ROUTE_36 ; untouched
	const EVENT_ECRUTEAK_TIN_TOWER_ENTRANCE_WANDERING_SAGE ; untouched
	const EVENT_TIN_TOWER_1F_SUICUNE ; untouched
	const EVENT_TIN_TOWER_1F_ENTEI ; untouched
	const EVENT_TIN_TOWER_1F_RAIKOU ; untouched
	const EVENT_TIN_TOWER_1F_EUSINE ; untouched
	const EVENT_TIN_TOWER_1F_WISE_TRIO_1 ; untouched
	const EVENT_ILEX_FOREST_X_ATTACK ; untouched
	const EVENT_ILEX_FOREST_ANTIDOTE ; untouched
	const EVENT_ILEX_FOREST_ETHER ; untouched
	const EVENT_ROUTE_34_NUGGET ; untouched
	const EVENT_DRAGONS_DEN_B1F_FULL_HEAL ; untouched
	const EVENT_DRAGONS_DEN_B1F_PROTEIN ; untouched
	const EVENT_SILVER_CAVE_ROOM_1_ULTRA_BALL ; untouched
	const EVENT_SILVER_CAVE_ROOM_2_CALCIUM ; untouched
	const EVENT_SILVER_CAVE_ROOM_2_ULTRA_BALL ; untouched
	const EVENT_SILVER_CAVE_ROOM_2_PP_UP ; untouched
	const EVENT_TIN_TOWER_1F_WISE_TRIO_2 ; untouched
	const EVENT_TIN_TOWER_6F_MAX_POTION ; untouched
	const EVENT_TIN_TOWER_9F_HP_UP ; untouched
	const EVENT_MOUNT_MORTAR_B2F_IRON ; untouched
	const EVENT_MOUNT_MORTAR_B2F_ULTRA_BALL ; untouched
	const EVENT_MOUNT_MORTAR_B1F_FULL_RESTORE ; untouched
	const EVENT_MOUNT_MORTAR_B1F_MAX_ETHER ; untouched
	const EVENT_MOUNT_MORTAR_B1F_PP_UP ; untouched
	const EVENT_RADIO_TOWER_5F_ULTRA_BALL ; untouched
	const EVENT_ROCKET_TOWER_OUTSIDE_SAILOR ; untouched

; Kanto story events ; untouched
	const EVENT_GOT_NUGGET_FROM_GUY ; untouched
	const EVENT_RETURNED_MACHINE_PART ; untouched
	const EVENT_MET_MANAGER_AT_POWER_PLANT ; untouched
	const EVENT_MET_ROCKET_GRUNT_AT_CERULEAN_GYM ; untouched
	const EVENT_MET_REDS_MOM ; untouched
	const EVENT_RESTORED_POWER_TO_KANTO ; untouched
	const EVENT_GOT_COINS_FROM_GAMBLER_AT_CELADON ; untouched
	const EVENT_MET_COPYCAT_FOUND_OUT_ABOUT_LOST_ITEM ; untouched
	const EVENT_RETURNED_LOST_ITEM_TO_COPYCAT ; untouched
	const EVENT_GOT_PASS_FROM_COPYCAT ; untouched
	const EVENT_GOT_LOST_ITEM_FROM_FAN_CLUB ; untouched
	const EVENT_LISTENED_TO_FAN_CLUB_PRESIDENT_BUT_BAG_WAS_FULL ; untouched
	const EVENT_LISTENED_TO_FAN_CLUB_PRESIDENT ; untouched
	const EVENT_TALKED_TO_SEAFOAM_GYM_GUIDE_ONCE ; untouched
	const EVENT_ENABLE_DIPLOMA_PRINTING ; untouched
	const EVENT_CINNABAR_ROCKS_CLEARED ; untouched
	const EVENT_CLEARED_NUGGET_BRIDGE ; untouched
	const EVENT_TALKED_TO_WARDENS_GRANDDAUGHTER ; untouched
	const EVENT_GOT_TM03_CURSE ; untouched
	const EVENT_GOT_CLEANSE_TAG ; untouched
	const EVENT_GOT_TM19_GIGA_DRAIN ; untouched
	const EVENT_GOT_TM06_TOXIC ; untouched
	const EVENT_GOT_TM07_ZAP_CANNON ; untouched
	const EVENT_GOT_TM42_DREAM_EATER ; untouched
	const EVENT_TALKED_TO_OAK_IN_KANTO ; untouched
	const EVENT_GOT_HP_UP_FROM_VERMILION_GUY ; untouched
	const EVENT_GOT_TM29_PSYCHIC ; untouched

; Legendaries
	const EVENT_FOUGHT_SUICUNE
	const EVENT_FOUGHT_ENTEI
	const EVENT_FOUGHT_RAIKOU
	const EVENT_FOUGHT_DOGS
	const EVENT_FOUGHT_ARTICUNO
	const EVENT_FOUGHT_ZAPDOS
	const EVENT_FOUGHT_MEWTWO
	const EVENT_FOUGHT_MEW
	const EVENT_FOUGHT_LUGIA
	const EVENT_FOUGHT_HO_OH
	const EVENT_SET_WHEN_FOUGHT_HO_OH
	
; Kurt Apricorn events
	const EVENT_GAVE_KURT_RED_APRICORN
	const EVENT_GAVE_KURT_BLU_APRICORN
	const EVENT_GAVE_KURT_YLW_APRICORN
	const EVENT_GAVE_KURT_GRN_APRICORN
	const EVENT_GAVE_KURT_WHT_APRICORN
	const EVENT_GAVE_KURT_BLK_APRICORN
	const EVENT_GAVE_KURT_PNK_APRICORN
	
; Phone events
	const EVENT_JACK_ASKED_FOR_PHONE_NUMBER
	const EVENT_BEVERLY_ASKED_FOR_PHONE_NUMBER
	const EVENT_HUEY_ASKED_FOR_PHONE_NUMBER
	const EVENT_GOT_PROTEIN_FROM_HUEY
	const EVENT_GOT_HP_UP_FROM_JOEY
	const EVENT_GOT_IRON_FROM_PARRY
	const EVENT_GOT_CALCIUM_FROM_ERIN
	const EVENT_KENJI_ON_BREAK
	const EVENT_GAVEN_ASKED_FOR_PHONE_NUMBER
	const EVENT_BETH_ASKED_FOR_PHONE_NUMBER
	const EVENT_JOSE_ASKED_FOR_PHONE_NUMBER
	const EVENT_REENA_ASKED_FOR_PHONE_NUMBER
	const EVENT_JOEY_ASKED_FOR_PHONE_NUMBER
	const EVENT_WADE_ASKED_FOR_PHONE_NUMBER
	const EVENT_RALPH_ASKED_FOR_PHONE_NUMBER
	const EVENT_LIZ_ASKED_FOR_PHONE_NUMBER
	const EVENT_ANTHONY_ASKED_FOR_PHONE_NUMBER
	const EVENT_TODD_ASKED_FOR_PHONE_NUMBER
	const EVENT_GINA_ASKED_FOR_PHONE_NUMBER
	const EVENT_IRWIN_ASKED_FOR_PHONE_NUMBER
	const EVENT_ARNIE_ASKED_FOR_PHONE_NUMBER
	const EVENT_ALAN_ASKED_FOR_PHONE_NUMBER
	const EVENT_DANA_ASKED_FOR_PHONE_NUMBER
	const EVENT_CHAD_ASKED_FOR_PHONE_NUMBER
	const EVENT_DEREK_ASKED_FOR_PHONE_NUMBER
	const EVENT_TULLY_ASKED_FOR_PHONE_NUMBER
	const EVENT_BRENT_ASKED_FOR_PHONE_NUMBER
	const EVENT_TIFFANY_ASKED_FOR_PHONE_NUMBER
	const EVENT_WILTON_ASKED_FOR_PHONE_NUMBER
	const EVENT_KENJI_ASKED_FOR_PHONE_NUMBER
	const EVENT_PARRY_ASKED_FOR_PHONE_NUMBER
	const EVENT_ERIN_ASKED_FOR_PHONE_NUMBER
	const EVENT_BUENA_OFFERED_HER_PHONE_NUMBER_NO_BLUE_CARD
	
; Ruins of Alph puzzles
	const EVENT_SOLVED_HO_OH_PUZZLE
	const EVENT_SOLVED_KABUTO_PUZZLE
	const EVENT_SOLVED_OMANYTE_PUZZLE
	const EVENT_SOLVED_AERODACTYL_PUZZLE
	
; Decorations
	const EVENT_DECO_BED_1
	const EVENT_DECO_BED_2
	const EVENT_DECO_BED_3
	const EVENT_DECO_BED_4
	const EVENT_DECO_CARPET_1
	const EVENT_DECO_CARPET_2
	const EVENT_DECO_CARPET_3
	const EVENT_DECO_CARPET_4
	const EVENT_DECO_PLANT_1
	const EVENT_DECO_PLANT_2
	const EVENT_DECO_PLANT_3
	const EVENT_DECO_POSTER_1
	const EVENT_DECO_POSTER_2
	const EVENT_DECO_POSTER_3
	const EVENT_DECO_POSTER_4
	const EVENT_DECO_FAMICOM
	const EVENT_DECO_SNES
	const EVENT_DECO_N64
	const EVENT_DECO_VIRTUAL_BOY
	const EVENT_DECO_PIKACHU_DOLL
	const EVENT_DECO_SURFING_PIKACHU_DOLL
	const EVENT_DECO_CLEFAIRY_DOLL
	const EVENT_DECO_JIGGLYPUFF_DOLL
	const EVENT_DECO_BULBASAUR_DOLL
	const EVENT_DECO_CHARMANDER_DOLL
	const EVENT_DECO_SQUIRTLE_DOLL
	const EVENT_DECO_POLIWAG_DOLL
	const EVENT_DECO_DIGLETT_DOLL
	const EVENT_DECO_STARMIE_DOLL
	const EVENT_DECO_MAGIKARP_DOLL
	const EVENT_DECO_ODDISH_DOLL
	const EVENT_DECO_GENGAR_DOLL
	const EVENT_DECO_SHELLDER_DOLL
	const EVENT_DECO_GRIMER_DOLL
	const EVENT_DECO_VOLTORB_DOLL
	const EVENT_DECO_WEEDLE_DOLL
	const EVENT_DECO_UNOWN_DOLL
	const EVENT_DECO_GEODUDE_DOLL
	const EVENT_DECO_MACHOP_DOLL
	const EVENT_DECO_TENTACOOL_DOLL
	const EVENT_PLAYERS_ROOM_POSTER
	const EVENT_DECO_GOLD_TROPHY
	const EVENT_DECO_SILVER_TROPHY
	const EVENT_DECO_BIG_SNORLAX_DOLL
	const EVENT_DECO_BIG_ONIX_DOLL
	const EVENT_DECO_BIG_LAPRAS_DOLL
	
; Trainer flags: Beauty
	const EVENT_BEAT_BEAUTY_VICTORIA
	const EVENT_BEAT_BEAUTY_SAMANTHA
	const EVENT_BEAT_BEAUTY_JULIE
	const EVENT_BEAT_BEAUTY_JACLYN
	const EVENT_BEAT_BEAUTY_BRENDA
	const EVENT_BEAT_BEAUTY_CASSIE
	const EVENT_BEAT_BEAUTY_CAROLINE
	const EVENT_BEAT_BEAUTY_CARLENE
	const EVENT_BEAT_BEAUTY_JESSICA
	const EVENT_BEAT_BEAUTY_RACHAEL
	const EVENT_BEAT_BEAUTY_ANGELICA
	const EVENT_BEAT_BEAUTY_KENDRA
	const EVENT_BEAT_BEAUTY_VERONICA
	const EVENT_BEAT_BEAUTY_JULIA
	const EVENT_BEAT_BEAUTY_THERESA
	const EVENT_BEAT_BEAUTY_VALERIE
	const EVENT_BEAT_BEAUTY_OLIVIA
	
; Biker
	const EVENT_BEAT_BIKER_BENNY
	const EVENT_BEAT_BIKER_KAZU
	const EVENT_BEAT_BIKER_DWAYNE
	const EVENT_BEAT_BIKER_HARRIS
	const EVENT_BEAT_BIKER_ZEKE
	const EVENT_BEAT_BIKER_CHARLES
	const EVENT_BEAT_BIKER_RILEY
	const EVENT_BEAT_BIKER_JOEL
	const EVENT_BEAT_BIKER_GLENN
	
; Bird Keeper
	const EVENT_BEAT_BIRD_KEEPER_ROD
	const EVENT_BEAT_BIRD_KEEPER_ABE
	const EVENT_BEAT_BIRD_KEEPER_BRYAN
	const EVENT_BEAT_BIRD_KEEPER_THEO
	const EVENT_BEAT_BIRD_KEEPER_TOBY
	const EVENT_BEAT_BIRD_KEEPER_DENIS
	const EVENT_BEAT_BIRD_KEEPER_VANCE
	const EVENT_BEAT_BIRD_KEEPER_HANK
	const EVENT_BEAT_BIRD_KEEPER_ROY
	const EVENT_BEAT_BIRD_KEEPER_BORIS
	const EVENT_BEAT_BIRD_KEEPER_BOB
	const EVENT_BEAT_BIRD_KEEPER_JOSE
	const EVENT_BEAT_BIRD_KEEPER_PETER
	const EVENT_BEAT_BIRD_KEEPER_JOSE2
	const EVENT_BEAT_BIRD_KEEPER_PERRY
	const EVENT_BEAT_BIRD_KEEPER_BRET
	const EVENT_BEAT_BIRD_KEEPER_JOSE3
	
; Blackbelt
	const EVENT_BEAT_BLACKBELT_KENJI2
	const EVENT_BEAT_BLACKBELT_YOSHI
	const EVENT_BEAT_BLACKBELT_KENJI3
	const EVENT_BEAT_BLACKBELT_LAO
	const EVENT_BEAT_BLACKBELT_NOB
	const EVENT_BEAT_BLACKBELT_KIYO
	const EVENT_BEAT_BLACKBELT_LUNG
	const EVENT_BEAT_BLACKBELT_KENJI
	const EVENT_BEAT_BLACKBELT_WAI
	
; Boarder
	const EVENT_BEAT_BOARDER_RONALD
	const EVENT_BEAT_BOARDER_BRAD
	const EVENT_BEAT_BOARDER_DOUGLAS

; Bug Catcher
	const EVENT_BEAT_BUG_CATCHER_DON
	const EVENT_BEAT_BUG_CATCHER_ROB
	const EVENT_BEAT_BUG_CATCHER_ED
	const EVENT_BEAT_BUG_CATCHER_WADE
	const EVENT_BEAT_BUG_CATCHER_BENNY
	const EVENT_BEAT_BUG_CATCHER_AL
	const EVENT_BEAT_BUG_CATCHER_JOSH
	const EVENT_BEAT_BUG_CATCHER_ARNIE
	const EVENT_BEAT_BUG_CATCHER_KEN
	const EVENT_BEAT_BUG_CATCHER_WADE2
	const EVENT_BEAT_BUG_CATCHER_WADE3
	const EVENT_BEAT_BUG_CATCHER_DOUG
	const EVENT_BEAT_BUG_CATCHER_ARNIE2
	const EVENT_BEAT_BUG_CATCHER_ARNIE3
	const EVENT_BEAT_BUG_CATCHER_WAYNE
	
; Burglar
	const EVENT_BEAT_BURGLAR_DUNCAN
	const EVENT_BEAT_BURGLAR_EDDIE
	const EVENT_BEAT_BURGLAR_COREY
	
; Camper
	const EVENT_BEAT_CAMPER_ROLAND
	const EVENT_BEAT_CAMPER_TODD
	const EVENT_BEAT_CAMPER_IVAN
	const EVENT_BEAT_CAMPER_ELLIOT
	const EVENT_BEAT_CAMPER_BARRY
	const EVENT_BEAT_CAMPER_LLOYD
	const EVENT_BEAT_CAMPER_DEAN
	const EVENT_BEAT_CAMPER_SID
	const EVENT_BEAT_CAMPER_HERVEY
	const EVENT_BEAT_CAMPER_DALE
	const EVENT_BEAT_CAMPER_TED
	const EVENT_BEAT_CAMPER_TODD2
	const EVENT_BEAT_CAMPER_TODD3
	const EVENT_BEAT_CAMPER_THOMAS
	const EVENT_BEAT_CAMPER_LEROY
	const EVENT_BEAT_CAMPER_DAVID
	const EVENT_BEAT_CAMPER_JOHN
	const EVENT_BEAT_CAMPER_JERRY
	const EVENT_BEAT_CAMPER_SPENCER
	const EVENT_BEAT_CAMPER_NEIL
	const EVENT_BEAT_CAMPER_QUENTIN
	
; CooltrainerF
	const EVENT_BEAT_COOLTRAINERF_GWEN
	const EVENT_BEAT_COOLTRAINERF_LOIS
	const EVENT_BEAT_COOLTRAINERF_FRAN
	const EVENT_BEAT_COOLTRAINERF_LOLA
	const EVENT_BEAT_COOLTRAINERF_KATE
	const EVENT_BEAT_COOLTRAINERF_IRENE
	const EVENT_BEAT_COOLTRAINERF_KELLY
	const EVENT_BEAT_COOLTRAINERF_JOYCE
	const EVENT_BEAT_COOLTRAINERF_BETH
	const EVENT_BEAT_COOLTRAINERF_REENA
	const EVENT_BEAT_COOLTRAINERF_MEGAN
	const EVENT_BEAT_COOLTRAINERF_BETH2
	const EVENT_BEAT_COOLTRAINERF_CAROL
	const EVENT_BEAT_COOLTRAINERF_QUINN
	const EVENT_BEAT_COOLTRAINERF_EMMA
	const EVENT_BEAT_COOLTRAINERF_CYBIL
	const EVENT_BEAT_COOLTRAINERF_JENN
	const EVENT_BEAT_COOLTRAINERF_BETH3
	const EVENT_BEAT_COOLTRAINERF_REENA2
	const EVENT_BEAT_COOLTRAINERF_REENA3
	const EVENT_BEAT_COOLTRAINERF_CARA
	
; CooltrainerM
	const EVENT_BEAT_COOLTRAINERM_NICK
	const EVENT_BEAT_COOLTRAINERM_AARON
	const EVENT_BEAT_COOLTRAINERM_PAUL
	const EVENT_BEAT_COOLTRAINERM_CODY
	const EVENT_BEAT_COOLTRAINERM_GAVEN2
	const EVENT_BEAT_COOLTRAINERM_GAVEN3
	const EVENT_BEAT_COOLTRAINERM_RYAN
	const EVENT_BEAT_COOLTRAINERM_JAKE
	const EVENT_BEAT_COOLTRAINERM_GAVEN
	const EVENT_BEAT_COOLTRAINERM_BLAKE
	const EVENT_BEAT_COOLTRAINERM_BRIAN
	const EVENT_BEAT_COOLTRAINERM_ERICK
	const EVENT_BEAT_COOLTRAINERM_ANDY
	const EVENT_BEAT_COOLTRAINERM_TYLER
	const EVENT_BEAT_COOLTRAINERM_SEAN
	const EVENT_BEAT_COOLTRAINERM_KEVIN
	const EVENT_BEAT_COOLTRAINERM_STEVE
	const EVENT_BEAT_COOLTRAINERM_ALLEN
	const EVENT_BEAT_COOLTRAINERM_DARIN
	
; ExecutiveF
	const EVENT_BEAT_ROCKET_EXECUTIVEF_1
	const EVENT_BEAT_ROCKET_EXECUTIVEF_2
	
; ExecutiveM
	const EVENT_BEAT_ROCKET_EXECUTIVEM_1
	const EVENT_BEAT_ROCKET_EXECUTIVEM_2
	const EVENT_BEAT_ROCKET_EXECUTIVEM_3
	const EVENT_BEAT_ROCKET_EXECUTIVEM_4
	
; Firebreather
	const EVENT_BEAT_FIREBREATHER_OTIS
	const EVENT_BEAT_FIREBREATHER_DICK
	const EVENT_BEAT_FIREBREATHER_NED
	const EVENT_BEAT_FIREBREATHER_BURT
	const EVENT_BEAT_FIREBREATHER_BILL
	const EVENT_BEAT_FIREBREATHER_WALT
	const EVENT_BEAT_FIREBREATHER_RAY
	const EVENT_BEAT_FIREBREATHER_LYLE
	const EVENT_BEAT_FIREBREATHER_FRANK
	
; Fisher
	const EVENT_BEAT_FISHER_JUSTIN
	const EVENT_BEAT_FISHER_RALPH
	const EVENT_BEAT_FISHER_ARNOLD
	const EVENT_BEAT_FISHER_KYLE
	const EVENT_BEAT_FISHER_HENRY
	const EVENT_BEAT_FISHER_MARVIN
	const EVENT_BEAT_FISHER_TULLY
	const EVENT_BEAT_FISHER_ANDRE
	const EVENT_BEAT_FISHER_RAYMOND
	const EVENT_BEAT_FISHER_WILTON
	const EVENT_BEAT_FISHER_EDGAR
	const EVENT_BEAT_FISHER_JONAH
	const EVENT_BEAT_FISHER_MARTIN
	const EVENT_BEAT_FISHER_STEPHEN
	const EVENT_BEAT_FISHER_BARNEY
	const EVENT_BEAT_FISHER_RALPH2
	const EVENT_BEAT_FISHER_RALPH3
	const EVENT_BEAT_FISHER_TULLY2
	const EVENT_BEAT_FISHER_TULLY3
	const EVENT_BEAT_FISHER_WILTON2
	const EVENT_BEAT_FISHER_SCOTT
	const EVENT_BEAT_FISHER_WILTON3

; Gentleman
	const EVENT_BEAT_GENTLEMAN_PRESTON
	const EVENT_BEAT_GENTLEMAN_EDWARD
	const EVENT_BEAT_GENTLEMAN_GREGORY
	const EVENT_BEAT_GENTLEMAN_VIRGIL
	const EVENT_BEAT_GENTLEMAN_ALFRED
	
; GruntF
	const EVENT_BEAT_ROCKET_GRUNTF_1
	const EVENT_BEAT_ROCKET_GRUNTF_2
	const EVENT_BEAT_ROCKET_GRUNTF_3
	const EVENT_BEAT_ROCKET_GRUNTF_4
	const EVENT_BEAT_ROCKET_GRUNTF_5
	
; GruntM
	const EVENT_BEAT_ROCKET_GRUNTM_1
	const EVENT_BEAT_ROCKET_GRUNTM_2
	const EVENT_BEAT_ROCKET_GRUNTM_3
	const EVENT_BEAT_ROCKET_GRUNTM_4
	const EVENT_BEAT_ROCKET_GRUNTM_5
	const EVENT_BEAT_ROCKET_GRUNTM_6
	const EVENT_BEAT_ROCKET_GRUNTM_7
	const EVENT_BEAT_ROCKET_GRUNTM_8
	const EVENT_BEAT_ROCKET_GRUNTM_9
	const EVENT_BEAT_ROCKET_GRUNTM_10
	const EVENT_BEAT_ROCKET_GRUNTM_11
	const EVENT_BEAT_ROCKET_GRUNTM_12
	const EVENT_BEAT_ROCKET_GRUNTM_13
	const EVENT_BEAT_ROCKET_GRUNTM_14
	const EVENT_BEAT_ROCKET_GRUNTM_15
	const EVENT_BEAT_ROCKET_GRUNTM_16
	const EVENT_BEAT_ROCKET_GRUNTM_17
	const EVENT_BEAT_ROCKET_GRUNTM_18
	const EVENT_BEAT_ROCKET_GRUNTM_19
	const EVENT_BEAT_ROCKET_GRUNTM_20
	const EVENT_BEAT_ROCKET_GRUNTM_21
	const EVENT_BEAT_ROCKET_GRUNTM_22
	const EVENT_BEAT_ROCKET_GRUNTM_23
	const EVENT_BEAT_ROCKET_GRUNTM_24
	const EVENT_BEAT_ROCKET_GRUNTM_25
	const EVENT_BEAT_ROCKET_GRUNTM_26
	const EVENT_BEAT_ROCKET_GRUNTM_27
	const EVENT_BEAT_ROCKET_GRUNTM_28
	const EVENT_BEAT_ROCKET_GRUNTM_29
	const EVENT_BEAT_ROCKET_GRUNTM_30
	const EVENT_BEAT_ROCKET_GRUNTM_31
	
; Guitarist
	const EVENT_BEAT_GUITARIST_CLYDE
	const EVENT_BEAT_GUITARIST_VINCENT

; Hiker
	const EVENT_BEAT_HIKER_ANTHONY2
	const EVENT_BEAT_HIKER_RUSSELL
	const EVENT_BEAT_HIKER_PHILLIP
	const EVENT_BEAT_HIKER_LEONARD
	const EVENT_BEAT_HIKER_ANTHONY
	const EVENT_BEAT_HIKER_BENJAMIN
	const EVENT_BEAT_HIKER_ERIK
	const EVENT_BEAT_HIKER_MICHAEL
	const EVENT_BEAT_HIKER_PARRY
	const EVENT_BEAT_HIKER_TIMOTHY
	const EVENT_BEAT_HIKER_BAILEY
	const EVENT_BEAT_HIKER_ANTHONY3
	const EVENT_BEAT_HIKER_TIM
	const EVENT_BEAT_HIKER_NOLAND
	const EVENT_BEAT_HIKER_SIDNEY
	const EVENT_BEAT_HIKER_KENNY
	const EVENT_BEAT_HIKER_JIM
	const EVENT_BEAT_HIKER_DANIEL
	const EVENT_BEAT_HIKER_PARRY2
	const EVENT_BEAT_HIKER_PARRY3
	
; Juggler
	const EVENT_BEAT_JUGGLER_IRWIN
	const EVENT_BEAT_JUGGLER_FRITZ
	const EVENT_BEAT_JUGGLER_HORTON
	const EVENT_BEAT_JUGGLER_IRWIN2
	const EVENT_BEAT_JUGGLER_IRWIN3

; Kimono Girl
	const EVENT_BEAT_KIMONO_GIRL_NAOKO
	const EVENT_BEAT_KIMONO_GIRL_SAYO
	const EVENT_BEAT_KIMONO_GIRL_ZUKI
	const EVENT_BEAT_KIMONO_GIRL_KUNI
	const EVENT_BEAT_KIMONO_GIRL_MIKI
	
; Lass
	const EVENT_BEAT_LASS_CARRIE
	const EVENT_BEAT_LASS_BRIDGET
	const EVENT_BEAT_LASS_ALICE
	const EVENT_BEAT_LASS_KRISE
	const EVENT_BEAT_LASS_CONNIE
	const EVENT_BEAT_LASS_LINDA
	const EVENT_BEAT_LASS_LAURA
	const EVENT_BEAT_LASS_SHANNON
	const EVENT_BEAT_LASS_MICHELLE
	const EVENT_BEAT_LASS_DANA
	const EVENT_BEAT_LASS_ELLEN
	const EVENT_BEAT_LASS_CONNIE2
	const EVENT_BEAT_LASS_CONNIE3
	const EVENT_BEAT_LASS_DANA2
	const EVENT_BEAT_LASS_DANA3
	
; Medium
	const EVENT_BEAT_MEDIUM_MARTHA
	const EVENT_BEAT_MEDIUM_GRACE
	const EVENT_BEAT_MEDIUM_BETHANY
	const EVENT_BEAT_MEDIUM_MARGRET
	const EVENT_BEAT_MEDIUM_ETHEL
	const EVENT_BEAT_MEDIUM_REBECCA
	const EVENT_BEAT_MEDIUM_DORIS
	
; Officer
	const EVENT_BEAT_OFFICER_KEITH
	const EVENT_BEAT_OFFICER_DIRK
	
; Picnicker
	const EVENT_BEAT_PICNICKER_LIZ
	const EVENT_BEAT_PICNICKER_GINA
	const EVENT_BEAT_PICNICKER_BROOKE
	const EVENT_BEAT_PICNICKER_KIM
	const EVENT_BEAT_PICNICKER_CINDY
	const EVENT_BEAT_PICNICKER_HOPE
	const EVENT_BEAT_PICNICKER_SHARON
	const EVENT_BEAT_PICNICKER_DEBRA
	const EVENT_BEAT_PICNICKER_GINA2
	const EVENT_BEAT_PICNICKER_ERIN
	const EVENT_BEAT_PICNICKER_LIZ2
	const EVENT_BEAT_PICNICKER_LIZ3
	const EVENT_BEAT_PICNICKER_HEIDI
	const EVENT_BEAT_PICNICKER_EDNA
	const EVENT_BEAT_PICNICKER_GINA3
	const EVENT_BEAT_PICNICKER_TIFFANY2
	const EVENT_BEAT_PICNICKER_TIFFANY3
	const EVENT_BEAT_PICNICKER_ERIN2
	const EVENT_BEAT_PICNICKER_TANYA
	const EVENT_BEAT_PICNICKER_TIFFANY
	const EVENT_BEAT_PICNICKER_ERIN3
	
; PokefanF
	const EVENT_BEAT_POKEFANF_BEVERLY
	const EVENT_BEAT_POKEFANF_RUTH
	const EVENT_BEAT_POKEFANF_BEVERLY2
	const EVENT_BEAT_POKEFANF_BEVERLY3
	const EVENT_BEAT_POKEFANF_GEORGIA
	const EVENT_BEAT_POKEFANF_JAMIE
	
; PokefanM
	const EVENT_BEAT_POKEFANM_WILLIAM
	const EVENT_BEAT_POKEFANM_DEREK
	const EVENT_BEAT_POKEFANM_ROBERT
	const EVENT_BEAT_POKEFANM_JOSHUA
	const EVENT_BEAT_POKEFANM_CARTER
	const EVENT_BEAT_POKEFANM_TREVOR
	const EVENT_BEAT_POKEFANM_BRANDON
	const EVENT_BEAT_POKEFANM_JEREMY
	const EVENT_BEAT_POKEFANM_COLIN
	const EVENT_BEAT_POKEFANM_DEREK2
	const EVENT_BEAT_POKEFANM_DEREK3
	const EVENT_BEAT_POKEFANM_ALEX
	const EVENT_BEAT_POKEFANM_REX
	const EVENT_BEAT_POKEFANM_ALLAN
	
; Pokemaniac
	const EVENT_BEAT_POKEMANIAC_LARRY
	const EVENT_BEAT_POKEMANIAC_ANDREW
	const EVENT_BEAT_POKEMANIAC_CALVIN
	const EVENT_BEAT_POKEMANIAC_SHANE
	const EVENT_BEAT_POKEMANIAC_BEN
	const EVENT_BEAT_POKEMANIAC_BRENT
	const EVENT_BEAT_POKEMANIAC_RON
	const EVENT_BEAT_POKEMANIAC_ETHAN
	const EVENT_BEAT_POKEMANIAC_BRENT2
	const EVENT_BEAT_POKEMANIAC_BRENT3
	const EVENT_BEAT_POKEMANIAC_ISAAC
	const EVENT_BEAT_POKEMANIAC_DONALD
	const EVENT_BEAT_POKEMANIAC_ZACH
	const EVENT_BEAT_POKEMANIAC_MILLER
	
; Psychic
	const EVENT_BEAT_PSYCHIC_NATHAN
	const EVENT_BEAT_PSYCHIC_FRANKLIN
	const EVENT_BEAT_PSYCHIC_HERMAN
	const EVENT_BEAT_PSYCHIC_FIDEL
	const EVENT_BEAT_PSYCHIC_GREG
	const EVENT_BEAT_PSYCHIC_NORMAN
	const EVENT_BEAT_PSYCHIC_MARK
	const EVENT_BEAT_PSYCHIC_PHIL
	const EVENT_BEAT_PSYCHIC_RICHARD
	const EVENT_BEAT_PSYCHIC_GILBERT
	const EVENT_BEAT_PSYCHIC_JARED
	const EVENT_BEAT_PSYCHIC_RODNEY
	
; Sage
	const EVENT_BEAT_SAGE_CHOW
	const EVENT_BEAT_SAGE_NICO
	const EVENT_BEAT_SAGE_JIN
	const EVENT_BEAT_SAGE_TROY
	const EVENT_BEAT_SAGE_JEFFREY
	const EVENT_BEAT_SAGE_PING
	const EVENT_BEAT_SAGE_EDMOND
	const EVENT_BEAT_SAGE_NEAL
	const EVENT_BEAT_SAGE_LI
	const EVENT_BEAT_SAGE_GAKU
	const EVENT_BEAT_SAGE_MASA
	const EVENT_BEAT_SAGE_KOJI
	
; Sailor
	const EVENT_BEAT_SAILOR_EUGENE
	const EVENT_BEAT_SAILOR_HUEY
	const EVENT_BEAT_SAILOR_TERRELL
	const EVENT_BEAT_SAILOR_KENT
	const EVENT_BEAT_SAILOR_ERNEST
	const EVENT_BEAT_SAILOR_JEFF
	const EVENT_BEAT_SAILOR_GARRETT
	const EVENT_BEAT_SAILOR_KENNETH
	const EVENT_BEAT_SAILOR_STANLY
	const EVENT_BEAT_SAILOR_HARRY
	const EVENT_BEAT_SAILOR_HUEY2
	const EVENT_BEAT_SAILOR_HUEY3
	
; Schoolboy
	const EVENT_BEAT_SCHOOLBOY_JACK
	const EVENT_BEAT_SCHOOLBOY_KIP
	const EVENT_BEAT_SCHOOLBOY_ALAN
	const EVENT_BEAT_SCHOOLBOY_JOHNNY
	const EVENT_BEAT_SCHOOLBOY_DANNY
	const EVENT_BEAT_SCHOOLBOY_TOMMY
	const EVENT_BEAT_SCHOOLBOY_DUDLEY
	const EVENT_BEAT_SCHOOLBOY_JOE
	const EVENT_BEAT_SCHOOLBOY_BILLY
	const EVENT_BEAT_SCHOOLBOY_CHAD
	const EVENT_BEAT_SCHOOLBOY_NATE
	const EVENT_BEAT_SCHOOLBOY_RICKY
	const EVENT_BEAT_SCHOOLBOY_JACK2
	const EVENT_BEAT_SCHOOLBOY_JACK3
	const EVENT_BEAT_SCHOOLBOY_ALAN2
	const EVENT_BEAT_SCHOOLBOY_ALAN3
	const EVENT_BEAT_SCHOOLBOY_CHAD2
	const EVENT_BEAT_SCHOOLBOY_CHAD3
	
; Scientist
	const EVENT_BEAT_SCIENTIST_ROSS
	const EVENT_BEAT_SCIENTIST_MITCH
	const EVENT_BEAT_SCIENTIST_JED
	const EVENT_BEAT_SCIENTIST_MARC
	const EVENT_BEAT_SCIENTIST_RICH
	
; Skier
	const EVENT_BEAT_SKIER_ROXANNE
	const EVENT_BEAT_SKIER_CLARISSA
	const EVENT_BEAT_SKIER_NATALIE
	
; Super Nerd
	const EVENT_BEAT_SUPER_NERD_STAN
	const EVENT_BEAT_SUPER_NERD_ERIC
	const EVENT_BEAT_SUPER_NERD_GREGG
	const EVENT_BEAT_SUPER_NERD_JAY
	const EVENT_BEAY_SUPER_NERD_DAVE
	const EVENT_BEAT_SUPER_NERD_SAM
	const EVENT_BEAT_SUPER_NERD_TOM
	const EVENT_BEAT_SUPER_NERD_PAT
	const EVENT_BEAT_SUPER_NERD_SHAWN
	const EVENT_BEAT_SUPER_NERD_TERU	
	const EVENT_BEAT_SUPER_NERD_HUGH
	const EVENT_BEAT_SUPER_NERD_MARKUS
	
; SwimmerF
	const EVENT_BEAT_SWIMMERF_ELAINE
	const EVENT_BEAT_SWIMMERF_PAULA
	const EVENT_BEAT_SWIMMERF_KAYLEE
	const EVENT_BEAT_SWIMMERF_SUSIE
	const EVENT_BEAT_SWIMMERF_DENISE
	const EVENT_BEAT_SWIMMERF_KARA
	const EVENT_BEAT_SWIMMERF_WENDY
	const EVENT_BEAT_SWIMMERF_LISA
	const EVENT_BEAT_SWIMMERF_JILL
	const EVENT_BEAT_SWIMMERF_MARY
	const EVENT_BEAT_SWIMMERF_KATIE
	const EVENT_BEAT_SWIMMERF_DAWN
	const EVENT_BEAT_SWIMMERF_TARA
	const EVENT_BEAT_SWIMMERF_NICOLE
	const EVENT_BEAT_SWIMMERF_LORI
	const EVENT_BEAT_SWIMMERF_JODY
	const EVENT_BEAT_SWIMMERF_NIKKI
	const EVENT_BEAT_SWIMMERF_DIANA
	const EVENT_BEAT_SWIMMERF_BRIANA
	
; SwimmerM
	const EVENT_BEAT_SWIMMERM_HAROLD
	const EVENT_BEAT_SWIMMERM_SIMON
	const EVENT_BEAT_SWIMMERM_RANDALL
	const EVENT_BEAT_SWIMMERM_CHARLIE
	const EVENT_BEAT_SWIMMERM_GEORGE
	const EVENT_BEAT_SWIMMERM_BERKE
	const EVENT_BEAT_SWIMMERM_KIRK
	const EVENT_BEAT_SWIMMERM_MATHEW
	const EVENT_BEAT_SWIMMERM_HAL
	const EVENT_BEAT_SWIMMERM_PATON
	const EVENT_BEAT_SWIMMERM_DARYL
	const EVENT_BEAT_SWIMMERM_WALTER
	const EVENT_BEAT_SWIMMERM_TONY
	const EVENT_BEAT_SWIMMERM_JEROME
	const EVENT_BEAT_SWIMMERM_TUCKER
	const EVENT_BEAT_SWIMMERM_RICK
	const EVENT_BEAT_SWIMMERM_CAMERON
	const EVENT_BEAT_SWIMMERM_SETH
	const EVENT_BEAT_SWIMMERM_JAMES
	const EVENT_BEAT_SWIMMERM_LEWIS
	const EVENT_BEAT_SWIMMERM_PARKER
	
; Teacher
	const EVENT_BEAT_TEACHER_COLETTE
	const EVENT_BEAT_TEACHER_HILLARY
	const EVENT_BEAT_TEACHER_SHIRLEY
	
; Twins
	const EVENT_BEAT_TWINS_AMY_AND_MAY
	const EVENT_BEAT_TWINS_ANN_AND_ANNE
	const EVENT_BEAT_TWINS_ANN_AND_ANNE2
	const EVENT_BEAT_TWINS_AMY_AND_MAY2
	const EVENT_BEAT_TWINS_JO_AND_ZOE
	const EVENT_BEAT_TWINS_JO_AND_ZOE2
	const EVENT_BEAT_TWINS_MEG_AND_PEG
	const EVENT_BEAT_TWINS_MEG_AND_PEG2
	const EVENT_BEAT_TWINS_LEA_AND_PIA
	
; Youngster
	const EVENT_BEAT_YOUNGSTER_JOEY
	const EVENT_BEAT_YOUNGSTER_MIKEY
	const EVENT_BEAT_YOUNGSTER_ALBERT
	const EVENT_BEAT_YOUNGSTER_GORDON
	const EVENT_BEAT_YOUNGSTER_SAMUEL
	const EVENT_BEAT_YOUNGSTER_IAN
	const EVENT_BEAT_YOUNGSTER_JOEY2
	const EVENT_BEAT_YOUNGSTER_JOEY3
	const EVENT_BEAT_YOUNGSTER_WARREN
	const EVENT_BEAT_YOUNGSTER_JIMMY
	const EVENT_BEAT_YOUNGSTER_OWEN
	const EVENT_BEAT_YOUNGSTER_JASON
	
; Johto Gym Leaders
	const EVENT_BEAT_CLAIR
	const EVENT_BEAT_PRYCE
	const EVENT_BEAT_JASMINE
	const EVENT_BEAT_CHUCK
	const EVENT_BEAT_MORTY
	const EVENT_BEAT_WHITNEY
	const EVENT_BEAT_BUGSY
	const EVENT_BEAT_FALKNER
	
; Kanto Gym Leaders
	const EVENT_BEAT_BLUE
	const EVENT_BEAT_BLAINE
	const EVENT_BEAT_JANINE
	const EVENT_BEAT_ERIKA
	const EVENT_BEAT_SABRINA
	const EVENT_BEAT_LTSURGE
	const EVENT_BEAT_MISTY
	const EVENT_BEAT_BROCK
	
; Elite Four and Champion
	const EVENT_BEAT_ELITE_4_WILL
	const EVENT_BEAT_ELITE_4_KOGA
	const EVENT_BEAT_ELITE_4_BRUNO
	const EVENT_BEAT_ELITE_4_KAREN
	const EVENT_BEAT_CHAMPION_LANCE
	
; Sprite visibility flags:
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.

; Johto items (placeholders)
	const EVENT_VIOLET_CITY_PP_UP
	const EVENT_VIOLET_CITY_RARE_CANDY
	const EVENT_SPROUT_TOWER_1F_PARLYZ_HEAL
	const EVENT_SPROUT_TOWER_2F_X_ACCURACY
	const EVENT_SPROUT_TOWER_3F_POTION
	const EVENT_SPROUT_TOWER_3F_ESCAPE_ROPE
	const EVENT_TIN_TOWER_3F_FULL_HEAL
	const EVENT_TIN_TOWER_4F_ULTRA_BALL
	const EVENT_TIN_TOWER_4F_PP_UP
	const EVENT_TIN_TOWER_4F_ESCAPE_ROPE
	const EVENT_TIN_TOWER_5F_RARE_CANDY
	const EVENT_TIN_TOWER_7F_MAX_REVIVE
	const EVENT_TIN_TOWER_8F_NUGGET
	const EVENT_TIN_TOWER_8F_MAX_ELIXIR
	const EVENT_TIN_TOWER_8F_FULL_RESTORE
	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_ULTRA_BALL
	const EVENT_NATIONAL_PARK_PARLYZ_HEAL
	const EVENT_NATIONAL_PARK_TM_DIG
	const EVENT_UNION_CAVE_1F_GREAT_BALL
	const EVENT_UNION_CAVE_1F_X_ATTACK
	const EVENT_UNION_CAVE_1F_POTION
	const EVENT_UNION_CAVE_1F_AWAKENING
	const EVENT_UNION_CAVE_B1F_TM_SWIFT
	const EVENT_UNION_CAVE_B1F_X_DEFEND
	const EVENT_UNION_CAVE_B2F_ELIXIR
	const EVENT_UNION_CAVE_B2F_HYPER_POTION
	const EVENT_GOT_TM08_ROCK_SMASH
	const EVENT_SLOWPOKE_WELL_B1F_SUPER_POTION
	const EVENT_SLOWPOKE_WELL_B2F_TM_RAIN_DANCE
	const EVENT_OLIVINE_LIGHTHOUSE_3F_ETHER ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_5F_RARE_CANDY ; DELETE
	const EVENT_OLIVINE_LIGHTHOUSE_5F_SUPER_REPEL ; DELETE
	const EVENT_OLIVINE_LIGHTHOUSE_5F_TM_SWAGGER ; DELETE
	const EVENT_OLIVINE_LIGHTHOUSE_6F_SUPER_POTION ; DELETE
	const EVENT_ILEX_FOREST_REVIVE
	const EVENT_GOLDENROD_UNDERGROUND_COIN_CASE
	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_SMOKE_BALL
	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_FULL_HEAL
	const EVENT_GOLDENROD_DEPT_STORE_B1F_ETHER
	const EVENT_GOLDENROD_DEPT_STORE_B1F_AMULET_COIN
	const EVENT_GOLDENROD_DEPT_STORE_B1F_BURN_HEAL
	const EVENT_GOLDENROD_DEPT_STORE_B1F_ULTRA_BALL
	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_MAX_ETHER
	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_TM_SLEEP_TALK
	const EVENT_MOUNT_MORTAR_1F_ETHER
	const EVENT_MOUNT_MORTAR_1F_REVIVE
	const EVENT_MOUNT_MORTAR_B2F_REVIVE
	const EVENT_MOUNT_MORTAR_B2F_ETHER
	const EVENT_MOUNT_MORTAR_B2F_HIDDEN_HYPER_POTION
	const EVENT_MOUNT_MORTAR_1F_ULTRA_BALL
	const EVENT_MOUNT_MORTAR_1F_IRON
	const EVENT_MOUNT_MORTAR_1F_NUGGET
	const EVENT_MOUNT_MORTAR_1F_MAX_POTION
	const EVENT_MOUNT_MORTAR_1F_HYPER_POTION
	const EVENT_MOUNT_MORTAR_1F_MAX_REVIVE
	const EVENT_MOUNT_MORTAR_1F_ESCAPE_ROPE
	const EVENT_MOUNT_MORTAR_1F_HIDDEN_MAX_REPEL
	const EVENT_MOUNT_MORTAR_B2F_ESCAPE_ROPE
	const EVENT_MOUNT_MORTAR_B2F_MAX_REVIVE
	const EVENT_MOUNT_MORTAR_B2F_HYPER_POTION
	const EVENT_MOUNT_MORTAR_2F_MAX_POTION
	const EVENT_MOUNT_MORTAR_2F_RARE_CANDY
	const EVENT_MOUNT_MORTAR_2F_TM_DEFENSE_CURL
	const EVENT_MOUNT_MORTAR_2F_DRAGON_SCALE
	const EVENT_MOUNT_MORTAR_2F_ELIXIR
	const EVENT_MOUNT_MORTAR_2F_ESCAPE_ROPE
	const EVENT_MOUNT_MORTAR_B1F_HYPER_POTION
	const EVENT_MOUNT_MORTAR_B1F_CARBOS
	const EVENT_WHIRL_ISLAND_NE_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_SW_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_B1F_FULL_RESTORE
	const EVENT_WHIRL_ISLAND_B1F_CARBOS
	const EVENT_WHIRL_ISLAND_B1F_CALCIUM
	const EVENT_WHIRL_ISLAND_B1F_NUGGET
	const EVENT_WHIRL_ISLAND_B1F_ESCAPE_ROPE
	const EVENT_WHIRL_ISLAND_B2F_FULL_RESTORE
	const EVENT_WHIRL_ISLAND_B2F_MAX_REVIVE
	const EVENT_WHIRL_ISLAND_B2F_MAX_ELIXIR
	const EVENT_SILVER_CAVE_ROOM_1_MAX_ELIXIR
	const EVENT_SILVER_CAVE_ROOM_1_PROTEIN
	const EVENT_SILVER_CAVE_ROOM_1_ESCAPE_ROPE
	const EVENT_SILVER_CAVE_ITEM_ROOMS_MAX_REVIVE
	const EVENT_SILVER_CAVE_ITEM_ROOMS_FULL_RESTORE
	const EVENT_DARK_CAVE_B1F_REVIVE
	const EVENT_DARK_CAVE_B1F_TM_SNORE
	const EVENT_VICTORY_ROAD_TM_EARTHQUAKE
	const EVENT_VICTORY_ROAD_MAX_REVIVE
	const EVENT_VICTORY_ROAD_FULL_RESTORE
	const EVENT_VICTORY_ROAD_FULL_HEAL
	const EVENT_VICTORY_ROAD_HP_UP
	const EVENT_DRAGONS_DEN_B1F_DRAGON_FANG
	const EVENT_TOHJO_FALLS_MOON_STONE
	const EVENT_ROUTE_26_MAX_ELIXIR
	const EVENT_ROUTE_27_TM_SOLARBEAM
	const EVENT_ROUTE_27_RARE_CANDY
	const EVENT_ROUTE_32_GREAT_BALL
	const EVENT_ROUTE_32_REPEL
	const EVENT_ROUTE_35_TM_ROLLOUT
	const EVENT_TIN_TOWER_4F_HIDDEN_MAX_POTION
	const EVENT_TIN_TOWER_5F_HIDDEN_FULL_RESTORE
	const EVENT_TIN_TOWER_5F_HIDDEN_CARBOS
	const EVENT_NATIONAL_PARK_HIDDEN_FULL_HEAL
	const EVENT_OLIVINE_LIGHTHOUSE_5F_HIDDEN_HYPER_POTION ; Johto items
	const EVENT_ILEX_FOREST_HIDDEN_ETHER
	const EVENT_ILEX_FOREST_HIDDEN_SUPER_POTION
	const EVENT_ILEX_FOREST_HIDDEN_FULL_HEAL
	const EVENT_GOLDENROD_UNDERGROUND_HIDDEN_PARLYZ_HEAL
	const EVENT_GOLDENROD_UNDERGROUND_HIDDEN_SUPER_POTION
	const EVENT_GOLDENROD_UNDERGROUND_HIDDEN_ANTIDOTE
	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_HIDDEN_MAX_POTION
	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_HIDDEN_REVIVE
	const EVENT_MOUNT_MORTAR_1F_HIDDEN_HYPER_POTION
	const EVENT_MOUNT_MORTAR_B2F_HIDDEN_MAX_REPEL
	const EVENT_MOUNT_MORTAR_2F_HIDDEN_FULL_RESTORE
	const EVENT_MOUNT_MORTAR_B1F_HIDDEN_MAX_REVIVE
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_RARE_CANDY
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_FULL_RESTORE
	const EVENT_SILVER_CAVE_ROOM_1_HIDDEN_DIRE_HIT
	const EVENT_SILVER_CAVE_ROOM_1_HIDDEN_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_HIDDEN_MAX_POTION
	const EVENT_VICTORY_ROAD_HIDDEN_MAX_POTION
	const EVENT_VICTORY_ROAD_HIDDEN_FULL_HEAL
	const EVENT_BLACKTHORN_CITY_HIDDEN_STARDUST
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_REVIVE
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_MAX_POTION
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_MAX_ELIXIR
	const EVENT_ROUTE_28_HIDDEN_RARE_CANDY
	const EVENT_ROUTE_31_HIDDEN_TINYMUSHROOM
	const EVENT_ROUTE_32_HIDDEN_GREAT_BALL
	const EVENT_ROUTE_32_HIDDEN_SUPER_POTION
	const EVENT_ROUTE_34_HIDDEN_RARE_CANDY
	const EVENT_ROUTE_34_HIDDEN_SUPER_POTION
	const EVENT_ROUTE_37_HIDDEN_ETHER
	const EVENT_ROUTE_39_HIDDEN_NUGGET
	const EVENT_ROUTE_40_HIDDEN_HYPER_POTION
	const EVENT_ROUTE_41_HIDDEN_MAX_ETHER
	const EVENT_VIOLET_CITY_HIDDEN_HYPER_POTION
	const EVENT_AZALEA_TOWN_HIDDEN_FULL_HEAL
	const EVENT_CIANWOOD_CITY_HIDDEN_REVIVE
	const EVENT_CIANWOOD_CITY_HIDDEN_MAX_ETHER
	const EVENT_SILVER_CAVE_OUTSIDE_HIDDEN_FULL_RESTORE
	
; Johto items
	const EVENT_VULPIX_POKEBALL_IN_ELMS_LAB
	const EVENT_POLIWAG_POKEBALL_IN_ELMS_LAB
	const EVENT_ODDISH_POKEBALL_IN_ELMS_LAB
	const EVENT_BURNED_TOWER_1F_GREAT_BALL
	const EVENT_BURNED_TOWER_1F_MOON_STONE
	const EVENT_BURNED_TOWER_1F_HIDDEN_HYPER_POTION
	const EVENT_BURNED_TOWER_1F_HIDDEN_ULTRA_BALL
	const EVENT_BURNED_TOWER_B1F_CARBOS
	const EVENT_BURNED_TOWER_B1F_CHARCOAL
	const EVENT_DARK_CAVE_1F_ETHER
	const EVENT_DARK_CAVE_1F_ESCAPE_ROPE
	const EVENT_DARK_CAVE_1F_LURE_BALL
	const EVENT_DARK_CAVE_1F_HYPER_POTION
	const EVENT_DARK_CAVE_1F_HIDDEN_EXP_CANDY_S
	const EVENT_ECRUTEAK_CITY_KINGS_ROCK
	const EVENT_ECRUTEAK_CITY_HIDDEN_MAX_ETHER
	const EVENT_ICE_PATH_1F_GREAT_BALL
	const EVENT_ICE_PATH_1F_IRON
	const EVENT_ICE_PATH_1F_TM20_ENDURE
	const EVENT_ICE_PATH_1F_X_ATTACK
	const EVENT_ICE_PATH_1F_HIDDEN_SUPER_POTION
	const EVENT_ICE_PATH_1F_HIDDEN_STARDUST
	const EVENT_ICE_PATH_B1F_ICE_HEAL
	const EVENT_ICE_PATH_B1F_ETHER
	const EVENT_ICE_PATH_B1F_HIDDEN_EXP_CANDY_S
	const EVENT_LAKE_OF_RAGE_X_SPEED
	const EVENT_LAKE_OF_RAGE_THUNDERSTONE
	const EVENT_LAKE_OF_RAGE_HIDDEN_FULL_HEAL
	const EVENT_LAKE_OF_RAGE_HIDDEN_EXP_CANDY_M
	const EVENT_LAKE_OF_RAGE_HIDDEN_MAX_POTION
	const EVENT_ROUTE_29_POTION
	const EVENT_ROUTE_29_REPEL
	const EVENT_ROUTE_29_HIDDEN_RAGECANDYBAR
	const EVENT_ROUTE_30_LIGHT_BALL
	const EVENT_ROUTE_30_ANTIDOTE
	const EVENT_ROUTE_30_HIDDEN_POTION
	const EVENT_ROUTE_31_POTION
	const EVENT_ROUTE_31_ULTRA_BALL
	const EVENT_ROUTE_31_STAR_PIECE
	const EVENT_ROUTE_38_SUPER_POTION
	const EVENT_ROUTE_38_HIDDEN_ETHER
	const EVENT_ROUTE_39_BARN_POISON_BARB
	const EVENT_ROUTE_42_ULTRA_BALL
	const EVENT_ROUTE_42_SUPER_POTION
	const EVENT_ROUTE_42_HIDDEN_NUGGET
	const EVENT_ROUTE_43_DIRE_HIT
	const EVENT_ROUTE_43_PP_UP
	const EVENT_ROUTE_43_HIDDEN_HEAVY_BALL
	const EVENT_ROUTE_44_GREAT_BALL
	const EVENT_ROUTE_44_ENERGYPOWDER
	const EVENT_ROUTE_44_NEVERMELTICE
	const EVENT_ROUTE_44_HIDDEN_ELIXIR
	const EVENT_ROUTE_45_PP_UP
	const EVENT_ROUTE_45_PARLYZ_HEAL
	const EVENT_ROUTE_45_X_SPECIAL
	const EVENT_ROUTE_45_HIDDEN_FRIEND_BALL
	const EVENT_ROUTE_45_HIDDEN_BERRY_JUICE
	const EVENT_ROUTE_46_GREAT_BALL
	const EVENT_ROUTE_46_HIDDEN_MAX_REVIVE
	const EVENT_TEAM_ROCKET_BASE_B1F_SMOKE_BALL
	const EVENT_TEAM_ROCKET_BASE_B1F_SLOWPOKETAIL
	const EVENT_TEAM_ROCKET_BASE_B1F_SPELL_TAG
	const EVENT_GOT_TM13_SNORE_FROM_MOOMOO_FARM
	const EVENT_HEALED_MOOMOO
	
; Johto toggles
	const EVENT_RIVAL_NEW_BARK_TOWN
	const EVENT_RIVAL_CHERRYGROVE_CITY
	const EVENT_RIVAL_AZALEA_TOWN
	const EVENT_RIVAL_TEAM_ROCKET_BASE
	const EVENT_RIVAL_GOLDENROD_UNDERGROUND
	const EVENT_RIVAL_VICTORY_ROAD
	const EVENT_RIVAL_OLIVINE_CITY
	const EVENT_RIVAL_SPROUT_TOWER
	const EVENT_RIVAL_DRAGONS_DEN
	const EVENT_PLAYERS_HOUSE_MOM_1
	const EVENT_PLAYERS_HOUSE_MOM_2
	const EVENT_PLAYERS_HOUSE_1F_NEIGHBOR
	const EVENT_PLAYERS_NEIGHBORS_HOUSE_NEIGHBOR
	const EVENT_MR_POKEMONS_HOUSE_OAK_TOGGLE
	const EVENT_ROUTE_29_TUSCANY_OF_TUESDAY
	const EVENT_ROUTE_29_GUARD_BLOCKING
	const EVENT_ROUTE_29_GUARD_MOVED
	const EVENT_ROUTE_30_YOUNGSTER_JOEY
	const EVENT_ROUTE_30_YOUNGSTER_MIKEY
	const EVENT_VIOLET_CITY_EARL
	const EVENT_EARLS_ACADEMY_EARL
	const EVENT_GOLDENROD_CITY_ROCKET_SCOUT
	const EVENT_GOLDENROD_CITY_ROCKET_TAKEOVER
	const EVENT_RADIO_TOWER_ROCKET_TAKEOVER
	const EVENT_GOLDENROD_CITY_CIVILIANS
	const EVENT_RADIO_TOWER_CIVILIANS_AFTER
	const EVENT_RADIO_TOWER_BLACKBELT_BLOCKS_STAIRS
	const EVENT_OLIVINE_LIGHTHOUSE_JASMINE ; DELETE
	const EVENT_OLIVINE_GYM_JASMINE ; DELETE
	const EVENT_LAKE_OF_RAGE_LANCE ; DELETE
	const EVENT_ROUTE_43_GATE_ROCKETS ; DELETE
	const EVENT_BLACKTHORN_CITY_SUPER_NERD_BLOCKS_GYM
	const EVENT_BLACKTHORN_CITY_SUPER_NERD_DOES_NOT_BLOCK_GYM
	const EVENT_DAY_CARE_MAN_IN_DAY_CARE
	const EVENT_DAY_CARE_MAN_ON_ROUTE_34
	const EVENT_DAY_CARE_MON_1
	const EVENT_DAY_CARE_MON_2
	const EVENT_ILEX_FOREST_FARFETCHD
	const EVENT_ROUTE_34_ILEX_FOREST_GATE_TEACHER_BEHIND_COUNTER
	const EVENT_ROUTE_34_ILEX_FOREST_GATE_LASS
	const EVENT_ROUTE_34_ILEX_FOREST_GATE_TEACHER_IN_WALKWAY
	const EVENT_ILEX_FOREST_LASS
	const EVENT_COPYCAT_1
	const EVENT_COPYCAT_2
	const EVENT_GOLDENROD_SALE_OFF
	const EVENT_GOLDENROD_SALE_ON
	const EVENT_ILEX_FOREST_APPRENTICE
	const EVENT_ILEX_FOREST_CHARCOAL_MASTER
	const EVENT_CHARCOAL_KILN_FARFETCH_D
	const EVENT_CHARCOAL_KILN_APPRENTICE
	const EVENT_CHARCOAL_KILN_BOSS
	const EVENT_ROUTE_36_SUDOWOODO
	const EVENT_AZALEA_TOWN_SLOWPOKES
	const EVENT_AZALEA_TOWN_SLOWPOKETAIL_ROCKET
	const EVENT_SLOWPOKE_WELL_SLOWPOKES
	const EVENT_SLOWPOKE_WELL_ROCKETS
	const EVENT_KURTS_HOUSE_SLOWPOKE
	const EVENT_ELMS_AIDE_IN_VIOLET_POKEMON_CENTER
	const EVENT_ELMS_AIDE_IN_LAB
	const EVENT_COP_IN_ELMS_LAB
	const EVENT_RUINS_OF_ALPH_OUTSIDE_SCIENTIST
	const EVENT_RUINS_OF_ALPH_RESEARCH_CENTER_SCIENTIST
	const EVENT_RUINS_OF_ALPH_INNER_CHAMBER_TOURISTS
	const EVENT_BLACKTHORN_GYM_BUTTON_1
	const EVENT_BLACKTHORN_GYM_BUTTON_2
	const EVENT_BLACKTHORN_GYM_BUTTON_3
	const EVENT_MYSTERY_GIFT_DELIVERY_GUY
	const EVENT_MET_BILL
	const EVENT_ECRUTEAK_POKE_CENTER_BILL_TOGGLE
	const EVENT_BUG_CATCHING_CONTESTANT_1A
	const EVENT_BUG_CATCHING_CONTESTANT_2A
	const EVENT_BUG_CATCHING_CONTESTANT_3A
	const EVENT_BUG_CATCHING_CONTESTANT_4A
	const EVENT_BUG_CATCHING_CONTESTANT_5A
	const EVENT_BUG_CATCHING_CONTESTANT_6A
	const EVENT_BUG_CATCHING_CONTESTANT_7A
	const EVENT_BUG_CATCHING_CONTESTANT_8A
	const EVENT_BUG_CATCHING_CONTESTANT_9A
	const EVENT_BUG_CATCHING_CONTESTANT_10A
	const EVENT_BUG_CATCHING_CONTESTANT_1B
	const EVENT_BUG_CATCHING_CONTESTANT_2B
	const EVENT_BUG_CATCHING_CONTESTANT_3B
	const EVENT_BUG_CATCHING_CONTESTANT_4B
	const EVENT_BUG_CATCHING_CONTESTANT_5B
	const EVENT_BUG_CATCHING_CONTESTANT_6B
	const EVENT_BUG_CATCHING_CONTESTANT_7B
	const EVENT_BUG_CATCHING_CONTESTANT_8B
	const EVENT_BUG_CATCHING_CONTESTANT_9B
	const EVENT_BUG_CATCHING_CONTESTANT_10B
	const EVENT_OLIVINE_PORT_SAILOR_AT_GANGWAY
	const EVENT_VERMILION_PORT_SAILOR_AT_GANGWAY
	const EVENT_FAST_SHIP_1F_GENTLEMAN
	const EVENT_FAST_SHIP_CABINS_NNW_NNE_NE_SAILOR
	const EVENT_FAST_SHIP_B1F_SAILOR_LEFT
	const EVENT_FAST_SHIP_B1F_SAILOR_RIGHT
	const EVENT_FAST_SHIP_CABINS_SE_SSE_GENTLEMAN
	const EVENT_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_TWIN_1
	const EVENT_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_TWIN_2
	const EVENT_OLIVINE_PORT_PASSAGE_POKEFAN_M
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_YOUNGSTER
	const EVENT_LAKE_OF_RAGE_CIVILIANS
	const EVENT_MAHOGANY_MART_OWNERS
	const EVENT_OLIVINE_PORT_SPRITES_BEFORE_HALL_OF_FAME
	const EVENT_OLIVINE_PORT_SPRITES_AFTER_HALL_OF_FAME
	const EVENT_FAST_SHIP_PASSENGERS_FIRST_TRIP
	const EVENT_FAST_SHIP_PASSENGERS_EASTBOUND
	const EVENT_FAST_SHIP_PASSENGERS_WESTBOUND
	const EVENT_TIN_TOWER_ROOF_HO_OH
	const EVENT_WHIRL_ISLAND_LUGIA_CHAMBER_LUGIA
	const EVENT_ICE_PATH_B2F_ARTICUNO
	const EVENT_KURTS_HOUSE_KURT_1
	const EVENT_KURTS_HOUSE_KURT_2
	const EVENT_SLOWPOKE_WELL_KURT
	const EVENT_PLAYERS_HOUSE_2F_CONSOLE
	const EVENT_PLAYERS_HOUSE_2F_DOLL_1
	const EVENT_PLAYERS_HOUSE_2F_DOLL_2
	const EVENT_PLAYERS_HOUSE_2F_BIG_DOLL
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_ROUTE_36_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_36_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_GOLDENROD_TRAIN_STATION_GENTLEMAN
	const EVENT_RUINS_OF_ALPH_KABUTO_CHAMBER_RECEPTIONIST
	const EVENT_OPENED_MT_SILVER
	const EVENT_FOUGHT_SNORLAX
	const EVENT_GOLDENROD_UNDERGROUND_GRANNY
	const EVENT_GOLDENROD_UNDERGROUND_GRAMPS
	const EVENT_GOLDENROD_UNDERGROUND_OLDER_HAIRCUT_BROTHER
	const EVENT_GOLDENROD_UNDERGROUND_YOUNGER_HAIRCUT_BROTHER
	const EVENT_MAHOGANY_TOWN_POKEFAN_M_BLOCKS_EAST
	const EVENT_MAHOGANY_TOWN_POKEFAN_M_BLOCKS_GYM
	const EVENT_ROUTE_32_FRIEDA_OF_FRIDAY
	const EVENT_ROUTE_36_ARTHUR_OF_THURSDAY
	const EVENT_ROUTE_37_SUNNY_OF_SUNDAY
	const EVENT_ROUTE_40_MONICA_OF_MONDAY
	const EVENT_LANCES_ROOM_OAK_AND_MARY
	const EVENT_UNION_CAVE_B2F_LAPRAS
	const EVENT_TEAM_ROCKET_DISBANDED
	const EVENT_RED_IN_MT_SILVER
	const EVENT_GOLDENROD_DEPT_STORE_5F_HAPPINESS_EVENT_LADY
	const EVENT_RANG_CLEAR_BELL_1
	const EVENT_RANG_CLEAR_BELL_2
	const EVENT_FLORIA_AT_FLOWER_SHOP
	const EVENT_FLORIA_AT_SUDOWOODO
	const EVENT_GOLDENROD_CITY_MOVE_TUTOR
	const EVENT_GOLDENROD_GAME_CORNER_MOVE_TUTOR
	const EVENT_ROUTE_39_BARN_BEEDRILL1_TOGGLE
	const EVENT_ROUTE_39_BARN_BEEDRILL2_TOGGLE
	const EVENT_ROUTE_39_BARN_BEEDRILL3_TOGGLE
	const EVENT_ROUTE_39_BEES_TOGGLE
	const EVENT_ROUTE_39_ROCKET_TOGGLE
	
; Kanto items
	const EVENT_PICKED_UP_FOCUS_BAND
	const EVENT_ROCK_TUNNEL_1F_ELIXIR
	const EVENT_ROCK_TUNNEL_1F_TM_STEEL_WING
	const EVENT_ROCK_TUNNEL_B1F_IRON
	const EVENT_ROCK_TUNNEL_B1F_PP_UP
	const EVENT_ROCK_TUNNEL_B1F_REVIVE
	const EVENT_ROUTE_2_DIRE_HIT
	const EVENT_ROUTE_2_MAX_POTION
	const EVENT_ROUTE_2_CARBOS
	const EVENT_ROUTE_2_ELIXIR
	const EVENT_ROUTE_4_HP_UP
	const EVENT_ROUTE_12_CALCIUM
	const EVENT_ROUTE_12_NUGGET
	const EVENT_ROUTE_15_PP_UP
	const EVENT_ROUTE_25_PROTEIN
	const EVENT_DIGLETTS_CAVE_HIDDEN_MAX_REVIVE
	const EVENT_UNDERGROUND_PATH_HIDDEN_FULL_RESTORE
	const EVENT_UNDERGROUND_PATH_HIDDEN_X_SPECIAL
	const EVENT_ROCK_TUNNEL_1F_HIDDEN_X_ACCURACY
	const EVENT_ROCK_TUNNEL_1F_HIDDEN_X_DEFEND
	const EVENT_ROCK_TUNNEL_B1F_HIDDEN_MAX_POTION
	const EVENT_OLIVINE_PORT_HIDDEN_PROTEIN
	const EVENT_VERMILION_PORT_HIDDEN_IRON
	const EVENT_MOUNT_MOON_SQUARE_HIDDEN_MOON_STONE
	const EVENT_ROUTE_2_HIDDEN_MAX_ETHER
	const EVENT_ROUTE_2_HIDDEN_FULL_HEAL
	const EVENT_ROUTE_2_HIDDEN_FULL_RESTORE
	const EVENT_ROUTE_2_HIDDEN_REVIVE
	const EVENT_ROUTE_4_HIDDEN_ULTRA_BALL
	const EVENT_ROUTE_9_HIDDEN_ETHER
	const EVENT_ROUTE_12_HIDDEN_ELIXIR
	const EVENT_ROUTE_13_HIDDEN_CALCIUM
	const EVENT_ROUTE_11_HIDDEN_REVIVE
	const EVENT_ROUTE_17_HIDDEN_MAX_ETHER
	const EVENT_ROUTE_17_HIDDEN_MAX_ELIXIR
	const EVENT_ROUTE_25_HIDDEN_POTION
	const EVENT_FOUND_LEFTOVERS_IN_CELADON_CAFE
	const EVENT_FOUND_BERSERK_GENE_IN_CERULEAN_CITY
	const EVENT_FOUND_MACHINE_PART_IN_CERULEAN_GYM
	const EVENT_VERMILION_CITY_HIDDEN_FULL_HEAL
	const EVENT_CELADON_CITY_HIDDEN_PP_UP
	const EVENT_CINNABAR_ISLAND_HIDDEN_RARE_CANDY
	const EVENT_GINA_GAVE_LEAF_STONE
	const EVENT_ALAN_GAVE_FIRE_STONE
	const EVENT_DANA_GAVE_THUNDERSTONE
	const EVENT_TULLY_GAVE_WATER_STONE
	const EVENT_TIFFANY_GAVE_PINK_BOW
	
; Kanto people
	const EVENT_ROUTE_24_ROCKET
	const EVENT_CERULEAN_GYM_ROCKET
	const EVENT_ROUTE_25_MISTY_BOYFRIEND
	const EVENT_TRAINERS_IN_CERULEAN_GYM
	const EVENT_VERMILION_CITY_SNORLAX
	const EVENT_ROUTE_5_6_POKEFAN_M_BLOCKS_UNDERGROUND_PATH
	const EVENT_SAFFRON_TRAIN_STATION_POPULATION
	const EVENT_COPYCATS_HOUSE_2F_DOLL
	const EVENT_VERMILION_FAN_CLUB_DOLL
	const EVENT_BLUE_IN_CINNABAR
	const EVENT_VIRIDIAN_GYM_BLUE
	const EVENT_SEAFOAM_GYM_GYM_GUIDE
	const EVENT_MT_MOON_SQUARE_ROCK
	const EVENT_MT_MOON_SQUARE_CLEFAIRY
	const EVENT_MT_MOON_RIVAL
	const EVENT_INDIGO_PLATEAU_POKECENTER_RIVAL
	const EVENT_TELEPORT_GUY
	
	const EVENT_GOT_SECRET_PONYTA

	const ROUTE_39_FARMHOUSE_FARMER_TOGGLE ; Johto toggles
	const EVENT_ROUTE_39_FARMHOUSE_TM04_ROLLOUT ; TMs
	const EVENT_MET_MR_POKEMON ; Chapter 0
	const EVENT_SHOWED_TATTERED_HAT_TO_MR_POKEMON ; Chapter 0
	const EVENT_ROUTE_39_CALCIUM ; Johto items
	const EVENT_DANCE_THEATRE_STONES_TOGGLE ; Johto toggles
	const EVENT_OLIVINE_SMEARGLE_HOUSE_GOT_SMEARGLE ; Chapter 3
	const EVENT_OLIVINE_SMEARGLE_HOUSE_SMEARGLE_TOGGLE ; Johto toggles
	const EVENT_OLIVINE_CAFE_LEFTOVERS ; Johto items
	const EVENT_OLIVINE_CAFE_GOT_FULL_HEAL ; Johto items
	const EVENT_OLIVINE_GYM_BOULDER_TOGGLE ; Johto toggles
	const EVENT_OLIVINE_LIGHTHOUSE_1F_HM02_SURF ; HMs
	const EVENT_OLIVINE_PORT_PASSAGE_HIDDEN_RAGECANDYBAR ; Johto items
	const EVENT_OLIVINE_CITY_HARD_STONE ; Johto items
	const EVENT_OLIVINE_CITY_HIDDEN_PP_UP ; Johto items
	const EVENT_RIVAL_OLIVINE_CITY_TOGGLE ; Johto toggles
	const EVENT_OPENED_OLIVINE_LIGHTHOUSE ; Chapter 4
	const EVENT_OLIVINE_GYM_TM47_STEEL_WING ; TMs
	const EVENT_BEAT_GUITARIST_RIDLEY ; Guitarist
	const EVENT_BEAT_BEAUTY_MELISSA ; Beauty
	const EVENT_BEAT_SUPER_NERD_JACOB ; Super Nerd
	const EVENT_PLAYTEST_MONS ; **TEST/DELETE**
	const EVENT_BEAT_THIEFTEST ; **TEST/DELETE**
	const EVENT_MET_MOMO_MILK_GUY ; Chapter 3
	const EVENT_GOT_MOOMOO_MILK_REWARD ; Chapter 3
	const EVENT_BEAT_RIVAL1_CHERRYGROVE ; Chapter 0
	const EVENT_OLIVINE_LIGHTHOUSE_1F_EVERSTONE ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_1F_ESCAPE_ROPE ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_2F_ULTRA_BALL ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_2F_HIDDEN_HYPER_POTION ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_3F_STAR_PIECE ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_3F_HIDDEN_FULL_HEAL ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_4F_SUPER_REPEL ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_4F_HIDDEN_REVIVE ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_5F_EXP_CANDY_M ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_5F_TM32_DOUBLE_TEAM ; TMs
	const EVENT_OLIVINE_LIGHTHOUSE_6F_MAX_ELIXIR ; Johto items
	const EVENT_OLIVINE_LIGHTHOUSE_6F_HIDDEN_PROTEIN ; Johto items

	const_next 3000

NUM_EVENTS EQU const_value
