; move ids
; indexes for:
; - Moves (see data/moves/moves.asm)
; - MoveNames (see data/moves/names.asm)
; - MoveDescriptions (see data/moves/descriptions.asm)
; - BattleAnimations (see data/moves/animations.asm)
	const_def
	const NO_MOVE      ; 00
	const POUND        ; 01
	const KARATE_CHOP  ; 02
	const DOUBLESLAP   ; 03
	const COMET_PUNCH  ; 04
	const MEGA_PUNCH   ; 05
	const PAY_DAY      ; 06
	const FIRE_PUNCH   ; 07
	const ICE_PUNCH    ; 08
	const THUNDERPUNCH ; 09
	const SCRATCH      ; 0a
	const VICEGRIP     ; 0b
	const GUILLOTINE   ; 0c
	const RAZOR_WIND   ; 0d
	const SWORDS_DANCE ; 0e
	const CUT          ; 0f
	const GUST         ; 10
	const WING_ATTACK  ; 11
	const WHIRLWIND    ; 12
	const FLY          ; 13
	const BIND         ; 14
	const SLAM         ; 15
	const VINE_WHIP    ; 16
	const STOMP        ; 17
	const DOUBLE_KICK  ; 18
	const MEGA_KICK    ; 19
	const JUMP_KICK    ; 1a
	const ROLLING_KICK ; 1b
	const SAND_ATTACK  ; 1c
	const HEADBUTT     ; 1d
	const HORN_ATTACK  ; 1e
	const FURY_ATTACK  ; 1f
	const HORN_DRILL   ; 20
	const TACKLE       ; 21
	const BODY_SLAM    ; 22
	const WRAP         ; 23
	const TAKE_DOWN    ; 24
	const THRASH       ; 25
	const DOUBLE_EDGE  ; 26
	const POISON_STING ; 27
	const TWINEEDLE    ; 28
	const PIN_MISSILE  ; 29
	const LEER         ; 2a
	const BITE         ; 2b
	const GROWL        ; 2c
	const ROAR         ; 2d
	const SING         ; 2e
	const SUPERSONIC   ; 2f
	const SONICBOOM    ; 30
	const DISABLE      ; 31
	const ACID         ; 32
	const EMBER        ; 33
	const FLAMETHROWER ; 34
	const MIST         ; 35
	const WATER_GUN    ; 36
	const HYDRO_PUMP   ; 37
	const SURF         ; 38
	const ICE_BEAM     ; 39
	const BLIZZARD     ; 3a
	const PSYBEAM      ; 3b
	const BUBBLEBEAM   ; 3c
	const AURORA_BEAM  ; 3d
	const HYPER_BEAM   ; 3e
	const PECK         ; 3f
	const DRILL_PECK   ; 40
	const SUBMISSION   ; 41
	const LOW_KICK     ; 42
	const COUNTER      ; 43
	const SEISMIC_TOSS ; 44
	const STRENGTH     ; 45
	const ABSORB       ; 46
	const MEGA_DRAIN   ; 47
	const LEECH_SEED   ; 48
	const GROWTH       ; 49
	const RAZOR_LEAF   ; 4a
	const SOLARBEAM    ; 4b
	const POISONPOWDER ; 4c
	const STUN_SPORE   ; 4d
	const SLEEP_POWDER ; 4e
	const PETAL_DANCE  ; 4f
	const STRING_SHOT  ; 50
	const DRAGON_RAGE  ; 51
	const FIRE_SPIN    ; 52
	const THUNDERSHOCK ; 53
	const THUNDERBOLT  ; 54
	const THUNDER_WAVE ; 55
	const THUNDER      ; 56
	const ROCK_THROW   ; 57
	const EARTHQUAKE   ; 58
	const FISSURE      ; 59
	const DIG          ; 5a
	const TOXIC        ; 5b
	const CONFUSION    ; 5c
	const PSYCHIC_M    ; 5d
	const HYPNOSIS     ; 5e
	const MEDITATE     ; 5f
	const AGILITY      ; 60
	const QUICK_ATTACK ; 61
	const RAGE         ; 62
	const TELEPORT     ; 63
	const NIGHT_SHADE  ; 64
	const MIMIC        ; 65
	const SCREECH      ; 66
	const DOUBLE_TEAM  ; 67
	const RECOVER      ; 68
	const MINIMIZE     ; 69
	const SMOKESCREEN  ; 6a
	const CONFUSE_RAY  ; 6b
	const DEFENSE_CURL ; 6c
	const BARRIER      ; 6d
	const LIGHT_SCREEN ; 6e
	const HAZE         ; 6f
	const REFLECT      ; 70
	const FOCUS_ENERGY ; 71
	const BIDE         ; 72
	const METRONOME    ; 73
	const MIRROR_MOVE  ; 74
	const SELFDESTRUCT ; 75
	const EGG_BOMB     ; 76
	const LICK         ; 77
	const SMOG         ; 78
	const SLUDGE       ; 79
	const BONE_CLUB    ; 7a
	const FIRE_BLAST   ; 7b
	const WATERFALL    ; 7c
	const CLAMP        ; 7d
	const SWIFT        ; 7e
	const SKULL_BASH   ; 7f
	const SPIKE_CANNON ; 80
	const CONSTRICT    ; 81
	const AMNESIA      ; 82
	const KINESIS      ; 83
	const SOFTBOILED   ; 84
	const HI_JUMP_KICK ; 85
	const GLARE        ; 86
	const DREAM_EATER  ; 87
	const POISON_GAS   ; 88
	const BARRAGE      ; 89
	const LEECH_LIFE   ; 8a
	const LOVELY_KISS  ; 8b
	const SKY_ATTACK   ; 8c
	const TRANSFORM    ; 8d
	const BUBBLE       ; 8e
	const DIZZY_PUNCH  ; 8f
	const SPORE        ; 90
	const FLASH        ; 91
	const PSYWAVE      ; 92
	const SPLASH       ; 93
	const ACID_ARMOR   ; 94
	const CRABHAMMER   ; 95
	const EXPLOSION    ; 96
	const FURY_SWIPES  ; 97
	const BONEMERANG   ; 98
	const REST         ; 99
	const ROCK_SLIDE   ; 9a
	const HYPER_FANG   ; 9b
	const CONVERSION   ; 9c
	const TRI_ATTACK   ; 9d
	const SUPER_FANG   ; 9e
	const SLASH        ; 9f
	const SUBSTITUTE   ; a0
	const STRUGGLE     ; a1
	const SKETCH       ; a2
	const TRIPLE_KICK  ; a3
	const THIEF        ; a4
	const NIGHTMARE    ; a5
	const FLAME_WHEEL  ; a6
	const SNORE        ; a7
	const CURSE        ; a8
	const FLAIL        ; a9
	const CONVERSION2  ; aa
	const AEROBLAST    ; ab
	const COTTON_SPORE ; ac
	const REVERSAL     ; ad
	const SPITE        ; ae
	const POWDER_SNOW  ; af
	const PROTECT      ; b0
	const MACH_PUNCH   ; b1
	const SCARY_FACE   ; b2
	const FEINT_ATTACK ; b3
	const SWEET_KISS   ; b4
	const BELLY_DRUM   ; b5
	const SLUDGE_BOMB  ; b6
	const MUD_SLAP     ; b7
	const OCTAZOOKA    ; b8
	const SPIKES       ; b9
	const ZAP_CANNON   ; ba
	const FORESIGHT    ; bb
	const DESTINY_BOND ; bc
	const PERISH_SONG  ; bd
	const ICY_WIND     ; be
	const DETECT       ; bf
	const BONE_RUSH    ; c0
	const LOCK_ON      ; c1
	const OUTRAGE      ; c2
	const SANDSTORM    ; c3
	const GIGA_DRAIN   ; c4
	const ENDURE       ; c5
	const CHARM        ; c6
	const ROLLOUT      ; c7
	const FALSE_SWIPE  ; c8
	const SWAGGER      ; c9
	const SPARK        ; ca
	const FURY_CUTTER  ; cb
	const STEEL_WING   ; cc
	const MEAN_LOOK    ; cd
	const ATTRACT      ; ce
	const SLEEP_TALK   ; cf
	const HEAL_BELL    ; d0
	const RETURN       ; d1
	const PRESENT      ; d2
	const FRUSTRATION  ; d3
	const SAFEGUARD    ; d4
	const PAIN_SPLIT   ; d5
	const SACRED_FIRE  ; d6
	const MAGNITUDE    ; d7
	const DYNAMICPUNCH ; d8
	const MEGAHORN     ; d9
	const DRAGONBREATH ; da
	const BATON_PASS   ; db
	const ENCORE       ; dc
	const PURSUIT      ; dd
	const RAPID_SPIN   ; de
	const SWEET_SCENT  ; df
	const IRON_TAIL    ; e0
	const METAL_CLAW   ; e1
	const VITAL_THROW  ; e2
	const MORNING_SUN  ; e3
	const SYNTHESIS    ; e4
	const MOONLIGHT    ; e5
	const HIDDEN_POWER ; e6
	const CROSS_CHOP   ; e7
	const TWISTER      ; e8
	const RAIN_DANCE   ; e9
	const SUNNY_DAY    ; ea
	const CRUNCH       ; eb
	const MIRROR_COAT  ; ec
	const PSYCH_UP     ; ed
	const EXTREMESPEED ; ee
	const ANCIENTPOWER ; ef
	const SHADOW_BALL  ; f0
	const FUTURE_SIGHT ; f1
	const ROCK_SMASH   ; f2
	const WHIRLPOOL    ; f3
	const BEAT_UP      ; f4
	const SIGNAL_BEAM  ; f5
	const X_SCISSOR	   ; f6
	const SHADOW_CLAW  ; f7
	const POISON_JAB   ; f8
	const AIR_SLASH	   ; f9
	const EARTH_POWER  ; fa
	const FLASH_CANNON ; fb
	const SEED_BOMB	   ; fc
	const ZEN_HEADBUTT ; fd
	const DARK_PULSE   ; fe
NUM_ATTACKS EQU const_value - 1

; Battle animations use the same constants as the moves up to this point
	const_next $ff
	const ANIM_SWEET_SCENT_2     ; ff
	const ANIM_THROW_POKE_BALL   ; 100
	const ANIM_SEND_OUT_MON      ; 101
	const ANIM_RETURN_MON        ; 102
	const ANIM_CONFUSED          ; 103
	const ANIM_SLP               ; 104
	const ANIM_BRN               ; 105
	const ANIM_PSN               ; 106
	const ANIM_SAP               ; 107
	const ANIM_FRZ               ; 108
	const ANIM_PAR               ; 109
	const ANIM_IN_LOVE           ; 10a
	const ANIM_IN_SANDSTORM      ; 10b
	const ANIM_IN_NIGHTMARE      ; 10c
	const ANIM_IN_WHIRLPOOL      ; 10d
; battle anims
	const ANIM_MISS              ; 10e
	const ANIM_ENEMY_DAMAGE      ; 10f
	const ANIM_ENEMY_STAT_DOWN   ; 110
	const ANIM_PLAYER_STAT_DOWN  ; 111
	const ANIM_PLAYER_DAMAGE     ; 112
	const ANIM_WOBBLE            ; 113
	const ANIM_SHAKE             ; 114
	const ANIM_HIT_CONFUSION     ; 115
NUM_BATTLE_ANIMS EQU const_value - 1

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_ENEMY_STAT_DOWN
	const BATTLEANIM_PLAYER_STAT_DOWN
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_WOBBLE
	const BATTLEANIM_SHAKE
	const BATTLEANIM_HIT_CONFUSION
